### ISSUE TITLE
Allen's temporal algebra?

### ISSUE THREAD

**Issue by garrettgman** [hadley/lubridate#115]
Add functions to recreate Allen's interval algebra for time intervals.

http://en.wikipedia.org/wiki/Allen's_interval_algebra

**Comment by jonboiser** [comment]
This looks like an interesting project, but doesn't lubridate already implement some of these methods? Off the top of my head, I know there is a way to check if intervals overlap.

Is the idea to implement the full set of relations in Allen's interval algebra?

**Comment by vspinu** [comment]
I think most if not all of that is already in. We have enough interval methods and if people want to add more, please request.
