### ISSUE TITLE
Use periods within seq

### ISSUE THREAD

**Issue by garrettgman** [hadley/lubridate#144]
It'd be great if this worked
````
start <- as.Date("2010-01-01")
end <- as.Date("2012-11-28")
seq(start, end, by = years(1))

## "2010-01-01"  "2011-01-01"  "2012-01-01" 
````

**Comment by andreas50** [comment]
The seq() function called in this example is base::seq.Date(). In other words, it is part of the R "base" package and not of the "lubridate" package. Making this code work would require a modification of the R base distribution.

**Comment by vspinu** [comment]
This is ancient and is unlikely to be implemented or fixed on our side. Closing as not supported by enough interest.
