### ISSUE TITLE
Splitting intervals using factors

### ISSUE THREAD

**Issue by ijlyttle** [hadley/lubridate#186]
As I understand, to be able to use `ddply()` to split according to a variable requires that the column be split by considering it as a factor.

I wish to use `ddply()` to be able to split by intervals, and I think I have found what is preventing me from doing that: 

```
inst_ref <- ymd("2001-01-01", tz="America/Chicago")
dur_ref <- dminutes(15)

intvl <- as.interval(rep(dur_ref, 4), inst_ref + dur_ref*seq(0,3))
as.factor(intvl)

[1] <NA> <NA> <NA> <NA>
Levels: 900
```

Is there something that can be done with intervals to allow them to be factored?

**Comment by vspinu** [comment]
Seems like this  one has been fixed in R

```
> as.factor(intvl)
[1] 2001-01-01 00:00:00 CST--2001-01-01 00:15:00 CST
[2] 2001-01-01 00:15:00 CST--2001-01-01 00:30:00 CST
[3] 2001-01-01 00:30:00 CST--2001-01-01 00:45:00 CST
[4] 2001-01-01 00:45:00 CST--2001-01-01 01:00:00 CST
4 Levels: 2001-01-01 00:00:00 CST--2001-01-01 00:15:00 CST ...
```
