### ISSUE TITLE
Adding 10 seconds to any date with 20:59:50 results in NA

### ISSUE THREAD

**Issue by mdagost** [hadley/lubridate#188]
I encountered something odd today, which looks to me like a bug.  I had been running R 2.15.2 with lubridate_1.2.0, I can do the following normal thing:

> ymd_hms('2013-05-01 20:59:50')+seconds(10)
[1] "2013-05-01 21:00:00 UTC"

However, with R 3.0.0 and lubridate_1.3.0, I get the following:

> ymd_hms('2013-05-01 20:59:50')+seconds(10)
[1] NA

I get an NA for any date that I try as long as the timestamp is 20:59:50 and I add seconds(10).  Actually, it looks like I get an NA for any timestamp (like 20:59:30) and interval combo in seconds (like seconds(30)) that would have a resulting timestamp of 21:00:00.  If the interval is in minutes or hours, it works though:

> ymd_hms('2013-05-01 20:00:00')+hours(1)
[1] "2013-05-01 21:00:00 UTC"
> ymd_hms('2013-05-01 20:50:00')+minutes(10)
[1] "2013-05-01 21:00:00 UTC"

Any ideas?

Michelangelo

**Comment by vspinu** [comment]
Finally fixed in 7941df8. This report was duplicated in #217 and #313.
