### ISSUE TITLE
Datetime becomes NA when calling "round_date" or "second"

### ISSUE THREAD

**Issue by stevencb** [hadley/lubridate#217]
Machine:            Mac Book Pro
Mac OS X:         10.8.5
Lubridate vers:    lubridate_1.3.2

The issue:

Setting second(a_posixct_dt) = 60 causes the time to become NA under the circumstance discussed below.  This does not occur on all versions / configurations (I didn't see this error on lubridate 1.2.0 using R 2.15.1 on a very old 17" MacBook Pro).

The bug originally appeared when calling "round_date" but this reproduces it as well.

<pre>
  > library(lubridate)
  > sessionInfo()
  R version 3.0.2 (2013-09-25)
  Platform: x86_64-apple-darwin10.8.0 (64-bit)

  locale:
  [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

  attached base packages:
  [1] stats graphics grDevices utils datasets methods base

  other attached packages:
  [1] lubridate_1.3.2

  loaded via a namespace (and not attached):
  [1] digest_0.6.4 memoise_0.1 plyr_1.8 stringr_0.6.2
  > version
  _
  platform x86_64-apple-darwin10.8.0
  arch x86_64
  os darwin10.8.0
  system x86_64, darwin10.8.0
  status
  major 3
  minor 0.2
  year 2013
  month 09
  day 25
  svn rev 63987
  language R
  version.string R version 3.0.2 (2013-09-25)
  nickname Frisbee Sailing
  > at = ymd_hms('2013-12-01 23:59:59')
  > at
  [1] "2013-12-01 23:59:59 UTC"
  > second(at)
  [1] 59
  > second(at) = 60
  > at
  [1] NA
  >
  > at = ymd_hms('2013-12-01 23:59:59')
  > at
  [1] "2013-12-01 23:59:59 UTC"
  > second(at)
  [1] 59
  > second(at) = 61
  > at
  [1] "2013-12-02 00:00:01 UTC"

  Here is what fails when calling "round_date":

  > at = ymd_hms('2013-12-01 23:59:59.9999')
  > round_date(at, unit='second')
  [1] NA

</pre>

**Comment by kykuo** [comment]
@vspinu can you try reproducing the errors explicitly calling `lubridate::second` and `lubridate::year`?

**Comment by stevencb** [comment]
I was wondering where things stand on this issue ?

Thanks.

**Comment by garrettgman** [comment]
I just opened the other issue, which appears to be a duplicate. The quickest way to get a fix will be to submit a pull request.
