### ISSUE TITLE
decimal_date(as.Date(NA)) throws an error

### ISSUE THREAD

**Issue by garrettgman** [hadley/lubridate#249]
"decimal_date(as.Date(NA)) throws an error instead of returning NA. (Admittedly the behavior is undocumented, but returning NA would be consistent with as.Date(NA) and a more useful result.)"

Reported by Paul Dunmore.

**Comment by vspinu** [comment]
> "decimal_date(as.Date(NA)) throws an error instead of returning NA. 

Not anymore. I have rewritten `decimal_date/date_decimal` today. This one seems to be miraculously fixed.

```
> decimal_date(as.Date(NA))
[1] NA
```
