### ISSUE TITLE
Feature request: epi-week

### ISSUE THREAD

**Issue by garrettgman** [hadley/lubridate#256]
I'm an epidemiologist with a focus on acute disease surveillance and often need to plot disease trends by a standard CDC "epi-week."  I haven't been able to find an existing function that creates this type of week from a date variable in a data frame, and it's a huge hindrance to transitioning from SAS where we have code for this purpose.  The only thing I have found is this discussion:
https://www.linkedin.com/groups/Date-function-in-R-is-77616.S.5875641964430376964
.

More on CDC epi-weeks (for example):
https://ibis.health.state.nm.us/resources/MMWRWeekCalendar.html

**Comment by chrismerkord** [comment]
This might need to be revisited. See my comment here: https://github.com/tidyverse/lubridate/issues/492#issuecomment-313532583
