### ISSUE TITLE
Add options "quarter","bimonthly", and "half-year" to floor_date/ceiling_date [Feature request]

### ISSUE THREAD

**Issue by mmeierer** [hadley/lubridate#268]
Add options "quarter","bimonthly", and "halfyear" to floor_date/ceiling_date. 

Thus any given date is rounded up/down to the first day of the quarter, bimonthly period (Jan-Feb, Mar-Apr, May-Jun, Jul-Aug, Sep-Oct, Nov-Dec) or half-year.

**Comment by jonboiser** [comment]
I would be interested in this feature too. Has there been any discussion on how it might be implemented? Are the boundaries of quarters simply 1/1, 4/1, 7/1, 10/1? Same with bimonthly (e.g. 1/1, 3/1, 5/1 ..., 11/1)?

**Comment by ptoche** [comment]
you know about ``round_date(x, "quarter")`` right?

**Comment by jonboiser** [comment]
I submitted the PR #303  that implemented the quarter-round/floor/ceil functionality. I believe this is still open since bimonthly, and halfyear are still unimplemented. This issue hasn't been touched in awhile, but I can look into adding those two missing pieces.

**Comment by vspinu** [comment]
> I can look into adding those two missing pieces.

Yes. Please. It would be useful indeed.
