### ISSUE TITLE
Add `qday` - day of the current quarter?

### ISSUE THREAD

**Issue by danielkrizian** [hadley/lubridate#278]
Similar to `wday`, `mday` or `yday`, why not add `qday` function as well?

`qday` would calculate the day of the current quarter for a specified time/date.

**Comment by jonboiser** [comment]
I commented on the discussion about [adding quarter to `floor_date`](https://github.com/hadley/lubridate/issues/239). Maybe that can be leveraged for this problem?

E.g. `qday(date)` is `date` minus `floor_date(date, "quarter")`, converted to integer.
