### ISSUE TITLE
Extending %m+% to weeks and days

### ISSUE THREAD

**Issue by larmarange** [hadley/lubridate#286]
So far, `%m+%` works only with periods containing only years and months. Therefore it's not possible to do something like `today() %m+% period(c(1,6),c("month","day)"`. 

Would it be possible to extend `%m+%` in a such way that previous example would be equal to `today %m+% period(1,"month") + period(6, "day")`?

I would also allow to write more generic code when the unit is not known.

**Comment by vspinu** [comment]
We need this one way or another to fix #235. So I am willing to give it a stab. The only issue is that we will need a convention, do we sum years/months first or HMS first. I think years/months first is a bit more meaningful because the function is called `%m%`:)
