### ISSUE TITLE
Inconsistency between period_to_seconds and seconds_to_period

### ISSUE THREAD

**Issue by larmarange** [hadley/lubridate#294]
`period_to_seconds ` considers that a year is equal 365 days while `seconds_to_period` considers that   a year is equal to 365.25 days.

Therefore: 

```r
> seconds_to_period(period_to_seconds(years(2)))
[1] "1y 0m 364d 18H 0M 0S"
```

**Comment by vspinu** [comment]
I don't quite understand why to use years in `seconds_to_period` in the first place. The code is not using `months`. I think it should not use years either.

**Comment by vspinu** [comment]
Ok. I am removing years from there. We will probably need to add an optional argument that users could  also use an approximate conversion to years and months.  I am not sure on a clean interface yet. Probably something like `units = c("day", "hour", "minute", "second")` which is a bit verbose,  and/or `units = "dhms"`.
