### ISSUE TITLE
'mday<-' missing?

### ISSUE THREAD

**Issue by ckluss** [hadley/lubridate#296]
Hi

`date <- ymd("2015-1-1")`
`lubridate::mday(date) <- 5`

with lubridate 1.4.0 I get
"Error : object 'mday<-' is not exported by 'namespace:lubridate'

`lubridate::yday(date) <- 5`
`lubridate::month(date) <- 5`
`lubridate::wday(date) <- 5`

are working without problems

thx for the great package!
Christof

**Comment by vspinu** [comment]
Thanks. It was a consequence of recent re-adjustments for `roxygen2` changes.
