### ISSUE TITLE
subset() on lubridate?

### ISSUE THREAD

**Issue by jubilatious1** [hadley/lubridate#300]
HI I'm running into an issue when using lubridate to add columns to create a date-time. I have a two column .csv file, with "Dates" and "Times". I use dmy() and hms() to convert to the appropriate class, and add these two columns together to give me a resulting date-time column. The reasoning for addition (instead of paste) is that I want a general purpose method in case times are >24 hrs. 

The problem comes when I subset: I see the answer has been shifted by 8 hours, which is my offset from UTC. I can correct the problem by setting HPC$Date2's tz = "Americas/LosAngeles", but I'd like code that can be used anywhere. FYI trying to set everything to UTC results in an error message with the HPC$Time2 column : "Error in `$<-.data.frame`(`*tmp*`, "Time2", value = c(0, 0, 0, 0, 0, 0,  :  replacement has 2075260 rows, data has 2075259" suggesting an OBO (off-by-one) error. 

Any help appreciated! 

Script at:
https://github.com/jubilatious1/lubridate/commit/88e992f7fcefa3f153b60b892c2a25a0ddcb772a

Data at:
https://github.com/jubilatious1/lubridate/commit/6247fcefe5649a8f7f149b4c83e00bf3b77c88b4

> HPC <- read.csv("./HPC.txt", header= TRUE, col.names = c("Date", "Time"), colClasses = c("character", "character"), dec = ".", stringsAsFactors = FALSE, na.strings = "?")

> HPC$Date2 <- dmy(HPC$Date, tz = "UTC")
> HPC$Time2 <- hms(HPC$Time)
> HPC$Date_Time <- (HPC$Date2 + HPC$Time2)
> head(HPC)
        Date     Time      Date2      Time2           Date_Time
1 16/12/2006 17:24:00 2006-12-16 17H 24M 0S 2006-12-16 17:24:00
2 16/12/2006 17:25:00 2006-12-16 17H 25M 0S 2006-12-16 17:25:00
3 16/12/2006 17:26:00 2006-12-16 17H 26M 0S 2006-12-16 17:26:00
4 16/12/2006 17:27:00 2006-12-16 17H 27M 0S 2006-12-16 17:27:00
5 16/12/2006 17:28:00 2006-12-16 17H 28M 0S 2006-12-16 17:28:00
6 16/12/2006 17:29:00 2006-12-16 17H 29M 0S 2006-12-16 17:29:00

> feb_1st2nd_2007 <- subset(HPC, HPC$Date_Time >= "2007-02-01 00:00:00 UTC" & HPC$Date_Time < "2007-02-03 00:00:00 UTC")
> head(feb_1st2nd_2007)
          Date     Time      Date2    Time2           Date_Time
67117 1/2/2007 08:00:00 2007-02-01 8H 0M 0S 2007-02-01 08:00:00
67118 1/2/2007 08:01:00 2007-02-01 8H 1M 0S 2007-02-01 08:01:00
67119 1/2/2007 08:02:00 2007-02-01 8H 2M 0S 2007-02-01 08:02:00
67120 1/2/2007 08:03:00 2007-02-01 8H 3M 0S 2007-02-01 08:03:00
67121 1/2/2007 08:04:00 2007-02-01 8H 4M 0S 2007-02-01 08:04:00
67122 1/2/2007 08:05:00 2007-02-01 8H 5M 0S 2007-02-01 08:05:00
> HPC$Time2 <- hms(HPC$Time, tz = TZ)
Error in `$<-.data.frame`(`*tmp*`, "Time2", value = c(0, 0, 0, 0, 0, 0,  : 
  replacement has 2075260 rows, data has 2075259
Calls: $<- -> $<-.data.frame

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] lubridate_1.3.3 RCurl_1.95-4.3  bitops_1.0-6   
loaded via a namespace (and not attached):
[1] digest_0.6.4  memoise_0.2.1 plyr_1.8.1    Rcpp_0.11.3   stringr_0.6.2 tools_3.1.2

**Comment by vspinu** [comment]
Sorry for coming so late on this one.

> HPC$Time2 <- hms(HPC$Time, tz = TZ)
> Error in $<-.data.frame(*tmp*, "Time2", value = c(0, 0, 0, 0, 0, 0, :
> replacement has 2075260 rows, data has 2075259
> Calls: $<- -> $<-.data.frame

This is your mistake. `tz` doesn't make sense for `hms` (there is no such argument), so your TZ is parsed to produce a vector of lenght `N + 1`.

> The problem comes when I subset: I see the answer has been shifted by 8 hours, which is my offset from UTC. 

I don't see this problem in your output. It's difficult to understand how to reproduce.

> HPC$Date2 <- dmy(HPC$Date, tz = "UTC")

You don't need tz="UTC" here. That's the default.

**Comment by jubilatious1** [comment]
Hi, and thank you for the comment! I uploaded the R-script and the data I tried to run:

Script at:
https://github.com/jubilatious1/lubridate/commit/88e992f7fcefa3f153b60b892c2a25a0ddcb772a

Data at:
https://github.com/jubilatious1/lubridate/commit/6247fcefe5649a8f7f149b4c83e00bf3b77c88b4

I try to isolate all timepoints for Feb 1st, 2007 and Feb 2nd, 2007, starting from midnight on the 1st and not including midnight on the 3rd. But the first datapoint that I get in the "subsetted" data is  8am on Feb 1, 2007. So the subset has been offset by my timezone:

feb_1st2nd_2007 <- subset(HPC, HPC$Date_Time >= "2007-02-01 00:00:00 UTC" & HPC$Date_Time < "2007-02-03 00:00:00 UTC")
head(feb_1st2nd_2007)
Date Time Date2 Time2 Date_Time
67117 1/2/2007 08:00:00 2007-02-01 8H 0M 0S 2007-02-01 08:00:00

**Comment by vspinu** [comment]
> But the first datapoint that I get in the "subsetted" data is 8am on Feb 1, 2007. So the subset has been offset by my timezone:

This is what you get when you use character vector in `>=`. The RHS is implicitly converted with  `as.POSIxct`. So you get:

```
as.POSIXct("2007-02-01 00:00:00 UTC")
[1] "2007-02-01 CET"
```
Which drives your result. This is how R works in general. Your option is to use `ymd("2007-02-01")` in your subseting

**Comment by jubilatious1** [comment]
Got it! Thank you!
