### ISSUE TITLE
month Maggio (May) not recognized with locale it_IT 

### ISSUE THREAD

**Issue by matteogrolla** [hadley/lubridate#306]
ymd("1975, maggio 12")
[1] NA
Warning message:
All formats failed to parse. No formats found. 
> dmy("12 maggio 1975")
[1] NA
Warning message:
All formats failed to parse. No formats found.

**Comment by vspinu** [comment]
What do `format(ymd("1975-05-12"), "%b")` and `format(ymd("1975-05-12"), "%B")` return?

I guess it's a capitalization issue. Does the `dmy("12 Maggio 1975")` work?

**Comment by matteogrolla** [comment]
dmy("12 Maggio 1975")
[1] NA
Warning message:
All formats failed to parse. No formats found. 

format(ymd("1975-05-12"), "%b")
[1] "Mag"

> format(ymd("1975-05-12"), "%B")
[1] "Maggio"

**Comment by vspinu** [comment]
That's strange. Can you parse it with `strptime("1975 Maggio 12", "%Y %B %d")`?

**Comment by matteogrolla** [comment]
strptime("1975 Maggio 12", "%Y %B %d")
[1] "1975-05-12 CET"

**Comment by vspinu** [comment]
Ok. It's our bug. I will install Italian locale and will try to reproduce and fix asap.

**Comment by matteogrolla** [comment]
Wonderful, thanks!

**Comment by vspinu** [comment]
It turned out that abreviated day for Sunday is "gio" which was interfering with "maggio". So `lubridate` was trying `%y-%b%a-%d` format. Should be fixed now.
