### ISSUE TITLE
Intervals calculated in group_by are assigned wrong units for some values 

### ISSUE THREAD

**Issue by eamcvey** [hadley/lubridate#309]
I have calculated an interval for my data based on grouped data in dplyr.  For each group I subtract max(dt) - min(dt), where dt is a POSIXct variable in my dataframe.  For 4 of my 5 groups, the result is between 1 and 2 days, but for the other group, the result is 10 hours.  When I look at the dataframe, however, the unit label for all rows is days (i.e. 1.25 days, 1.3 days, 1.1 days, 10 days, 1.9 days).  This is incorrect, because the value 10 is actually hours, not days.  I presume this has something to do with the fact that the interval calculations are happening independently within each group and therefore the units are decided independently, but there must be some requirement for the unit label to be the same for all values in a column?

I've included a minimal reproducible example:
```
library(lubridate)
library(dplyr)

structure(list(dt = structure(c(1426802400, 1426906800, 1426910400, 
1426946400, 1426946400, 1426950000, 1427086800, 1427090400, 1427198400
), tzone = "UTC", class = c("POSIXct", "POSIXt")), event_interval = structure(c(1L, 
1L, 2L, 2L, 2L, 3L, 3L, 4L, 4L), .Label = c("1", "2", "3", "4"
), class = "factor")), class = c("tbl_df", "tbl", "data.frame"
), row.names = c(NA, -9L), .Names = c("dt", "event_interval"))

ex_df %>% group_by(event_interval) %>% summarize(time_int = max(dt) - min(dt))
```

**Comment by vspinu** [comment]
This has to do with how difftime objects are concatenated. There is no "c" method  for difftime objects so the unit is dropped on concatenation:

```
> (d1 <- difftime(ymd("100130"),  ymd("100101")))
Time difference of 29 days
> (d2 <- difftime(ymd_hms("100101 200000"),  ymd_hms("100101 010000")))
Time difference of 19 hours
> str(c(d1, d2))
 num [1:2] 29 19
```

My guess is that `dplyr` handles attributes specifically and keeps only the attributes from the first group. You also get exactly the same problem with `data.table`. The solution is to use `difftime` with explicit units.

I am afraid it cannot be solved on lubridate side. @hadley, is this fixable on `dplyr` side? Would you prefer this to be moved to `dplyr` tracker?

**Comment by hadley** [comment]
I don't think there's much either dplyr or lubridate can do about this - the design of the difftime class is really rather poor. I'm not sure how we can avoid this problem.
