### ISSUE TITLE
31-10 as start date in interval generates an error in as.period(...,unit="month")

### ISSUE THREAD

**Issue by gd047** [hadley/lubridate#310]
When the start of an interval is 31-10 I get an error when I ask for the period in months, i.e. 

library(lubridate)
span <- new_interval(dmy("31/10/2002"),dmy("18/07/2005"))
as.period(span,unit="month")$month

Error in while (any(start + est * per > end)) est[start + est * per >  : 
  missing value where TRUE/FALSE needed

**Comment by vspinu** [comment]
Works fine for me. Please install the github version. CRAN is pretty outdated.
