### ISSUE TITLE
wday label problem?

### ISSUE THREAD

**Issue by jim-lutz** [hadley/lubridate#316]
Seems like label isn't working in wday().
> wday(ymd(080101) + days(-2:4), label = TRUE, abbr = TRUE)
Error in wday(ymd(80101) + days(-2:4), label = TRUE, abbr = TRUE) : 
  unused arguments (label = TRUE, abbr = TRUE)

> wday(ymd(080101) + days(-2:4))
[1] 1 2 3 4 5 6 7

lubridate_1.3.3

**Comment by vspinu** [comment]
Works in master. 

```
> wday(ymd(080101) + days(-2:4), label = TRUE, abbr = TRUE)
 [1] Sun   Mon   Tues  Wed   Thurs Fri   Sat  
 Levels: Sun < Mon < Tues < Wed < Thurs < Fri < Sat
```

**Comment by jim-lutz** [comment]
Vitalie,

After I posted the possible issue, I realized that wday in lubridate was 
later being overwritten by wday in data.table.  So I guess it's not 
really a problem, just something to be aware of.

thanks,
     Jim
