### ISSUE TITLE
as.period seconds error

### ISSUE THREAD

**Issue by init-random** [hadley/lubridate#320]
This looks like #284, which is closed but I see the following error with lubridate 1.3.3.

library(lubridate)
> a <- ymd_hms("2014-12-02 00:59:49 UTC"); b <- ymd_hms("2014-12-02 01:00:00 UTC")
> as.period(new_interval(a, b), unit='hours') # fine
[1] "11S"
> as.period(new_interval(a, b), unit='seconds')
Error in while (any(start + est * per < end)) est[start + est * per <  : 
  missing value where TRUE/FALSE needed
> traceback()
11: adjust(estimate, int, per)
10: divide_interval_by_period(e1, e2)
9: e1/e2
8: e1/e2
7: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
6: suppressMessages(e1/e2)
5: integer_divide_spans(e1, e2)
4: x%/%per(1)
3: x%/%per(1)
2: as.period(new_interval(a, b), unit = "seconds")
1: as.period(new_interval(a, b), unit = "seconds")

**Comment by vspinu** [comment]
It's fixed in master. 

```
> a <- ymd_hms("2014-12-02 00:59:49 UTC")
> b <- ymd_hms("2014-12-02 01:00:00 UTC")
> as.period(new_interval(a, b), unit='seconds')
[1] "11S"
> 
```

CRAN version is a bit outdated.

**Comment by init-random** [comment]
Yes, sorry. I just installed 1.4 from git where it is working fine now.
