### ISSUE TITLE
Infinite recursion due to DST

### ISSUE THREAD

**Issue by Andrestan** [hadley/lubridate#328]
Related issue: https://github.com/hadley/lubridate/issues/224

```
 lubridate::ymd_hms("2015-03-08 02:36:33.416278", tz="America/Los_Angeles")
```

This will result in an infinite recursion error.  With a few of these in a vector I was also getting a segmentation fault.

**Comment by vspinu** [comment]
What's your version of lubridate? I don't see this on `lubridate_1.4.0.9500`:

```
>  lubridate::ymd_hms("2015-03-08 02:36:33.416278", tz="America/Los_Angeles")
[1] NA
```

**Comment by Andrestan** [comment]
Is that the development version?  I have 1.3.3, the version that is on CRAN.

**Comment by vspinu** [comment]
Yes. CRAN version is quite outdated now. There will be a new CRAN push soon once the remaining couple of bugs are sorted out.
