### ISSUE TITLE
Leap Second for 2015

### ISSUE THREAD

**Issue by hansthompson** [hadley/lubridate#331]
Will lubridate account for the leap second in 2015?

Love lubridate btw.

**Comment by vspinu** [comment]
What do you mean more concretely? As long as your system accounts for it, lubridate will be fine.

**Comment by hansthompson** [comment]
I thought that lubridate had to account for all the leap time within its code. How will it know that the missing second is invalid if it isn't coded in? I'm not sure when the missing second will be but if I find out I will test it to find how lubridate handles it.

**Comment by vspinu** [comment]
There have been many leap seconds before. Lubridate doesn't deal with them explicitly because the R and OS take care of that with POSIX time objects.
