### ISSUE TITLE
Lubridate jumps over a month

### ISSUE THREAD

**Issue by adeldaoud** [hadley/lubridate#336]
Lubridate jumps over the 3ed month here:

as.period(interval(ymd("1985-12-31"),ymd("1986-01-01")))%/%months(1)
as.period(interval(ymd("1985-12-31"),ymd("1986-02-01")))%/%months(1)
as.period(interval(ymd("1985-12-31"),ymd("1986-03-01")))%/%months(1)
as.period(interval(ymd("1985-12-31"),ymd("1986-04-01")))%/%months(1)
as.period(interval(ymd("1985-12-31"),ymd("1986-05-01")))%/%months(1)

 This seems to be a bug, or at least an unexpected calculation.

**Comment by vspinu** [comment]
The problem is with the 

```
> as.period(interval(ymd("1985-12-31"),ymd("1986-03-01")))
[1] "2m -2d 0H 0M 0S"
```

There should be no negative days in `as.period` conversion.
