### ISSUE TITLE
Incrementing date

### ISSUE THREAD

**Issue by aneuhierl** [hadley/lubridate#337]
This works as expected:

`as.Date("1985-10-31") + months(3)`

whereas this doesn't work:

`as.Date("1985-10-31") + months(4)`

and produces NA.  It would be nice if something could be done to make lubridate usable to increment dates directly.

**Comment by vspinu** [comment]
```
as.Date("1985-10-31") %m+% months(4)
## [1] "1986-02-28"
```

Have a look at the doc for `%m+%` and `add_with_rollback` if you are using lubridate 1.4.0.
