### ISSUE TITLE
%within% is not working anymore

### ISSUE THREAD

**Issue by Caninus23** [hadley/lubridate#340]
Hi,
Is it possible, that %within% stopped working with dates and intervals? I encountered this issue in one of my scripts recently (it worked a month, and an R/packages update ago), and if I try the example from the vignette, it is also not working:

arrive <- ymd_hms("2011-06-04 12:00:00", tz = "Pacific/Auckland")
leave <- ymd_hms("2011-08-10 14:00:00", tz = "Pacific/Auckland")
auckland <- interval(arrive, leave)
jsm <- interval(ymd(20110720, tz = "Pacific/Auckland"), ymd(20110831, tz = "Pacific/Auckland"))
auckland %within% jsm

The error (use a german system):
Fehler in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘overlapsAny’ for signature ‘"Interval", "Interval"’

Is there a possible and easy way around?

Thanks!

**Comment by vspinu** [comment]
Works for me. What version is this? Try the github version.

**Comment by Caninus23** [comment]
It is 1.3.3 from C-RAN. Should be the same as the newest one here, or?
And it is with R Version 3.2.2 from August, 8th and IRanges 2.2.7.

**Comment by vspinu** [comment]
CRAN version is very oudated. Sorry.  Use `devtools::install_github("hadley/lubridate")` to get the newest code.
