### ISSUE TITLE
Add holiday detection functions, like 'isBizday' and 'isHoliday' in timeDate package

### ISSUE THREAD

**Issue by clbieganek** [hadley/lubridate#341]
Currently in order to test whether a POSIXct is a holiday, I have to first convert it to a `timeDate` object and then test it with `isBizday` or `isHoliday`. It would be nice if lubridate would have its own versions of these functions, so that we wouldn't have to mess around with `timeDate` objects.

**Comment by vspinu** [comment]
That's a good idea but there seems to be loads of functionality for holidays in `timeDate` package. That would mean porting all that lubridate or depending on `timeDate` package for its holidays databases.

**Comment by clbieganek** [comment]
Yeah, I agree that this is not a small request. The meat of the holiday functionality is in the holiday functions like `USLaborDay` and `USMemorialDay`, which internally call functions like `.nth.of.nday` and `.last.of.nday`, which in turn call functions like `.sdate` and `.sjulian`, etc, etc. However, it appears that the only point in this chain which actually uses `timeDate` objects is in the top level holiday functions, which end by taking the calculated date (`ans`) and spitting out `timeDate(as.character(ans))`. So the whole holiday calculation machinery could potentially just be copied over into lubridate, minus the `timeDate` conversion.

**Comment by hadley** [comment]
This feels out of scope for lubridate to me.  It really needs to live in a separate package because there will be a lot of data, which will need to be updated regularly.
