### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by zachmayer** [hadley/lubridate#342]
The release on CRAN is a lot older than the version on github.  Is a new CRAN release coming sometime, or will new features only be available on github?

**Comment by vspinu** [comment]
There are a couple of pending issues to fix first. The release was actually planned for June, but I was dragged into some unexpected projects and house reconstruction, and my summer was ruined.

In any case, I am starting getting more free hours these days, so by the end of the month expect a new release.

**Comment by zachmayer** [comment]
That's awesome.  What needs to be fixed?  Perhaps there's an issue I can help with.

**Comment by vspinu** [comment]
Look at all those issues labeled bugs.

**Comment by AlunHewinson** [comment]
+1
I was about to look into pull-requesting my enhancement to floor_date and ceiling_date adding "quarter" as a unit when I noticed that someone else did this seven months ago :smile:
Hope to see a new CRAN version as soon as there's time to smash those bugs.

Thanks for the great package.

**Comment by MansMeg** [comment]
Any news on when the package will be published on CRAN? Thanks for a great package!

**Comment by vspinu** [comment]
I am working on it. Slowly but steadily.  Some bugs take long time to fix. Once all critical bugs are fixed I will release.

**Comment by MansMeg** [comment]
Any news on release with CRAN? I'm the maintainer of a package that depend on lubridate 1.4 (mainly due to the leap year bug in 1.3.3) called sweidnumbr and now the CRAN people is asking me to update my package because of other reasons. Then I need to rewrite the package to put it on CRAN due to dependency with lubridate 1.4 if it will not be released soon.

Thanks for a great package!

**Comment by vspinu** [comment]
I will try to do it this weekend. There is one bug and a refactoring of lubridate constructors that holds it up.

**Comment by MansMeg** [comment]
Thats great! Please let me know when it is on CRAN. Thanks!

**Comment by vspinu** [comment]
Everything is fixed and refactoring done now. I still need to bring the news file up to date (it hasn't been updated for the past 1.5 years) and then check if any reverse dependences are broken. Depending on that it might take a bit to reach to the maintainers of broken packages before the actual CRAN release could happen. I will keep you posted.

**Comment by MansMeg** [comment]
Great! Thanks for the heads up!

**Comment by vspinu** [comment]
Lubridate 1.5.0 is out and propagated to CRAN. See the [release](https://github.com/hadley/lubridate/releases) notes. Thanks everyone for your patience.
