### ISSUE TITLE
Lubridate's month function has a bug

### ISSUE THREAD

**Issue by vkvarjun** [hadley/lubridate#345]
month() is failing for every case when it has to calculate feb-28(last day of feb)
> a = as.Date("2013-05-31")
> a
[1] "2013-05-31"
> month(a) = month(a) - 3
> a
[1] NA

> a = as.Date("2013-01-31")
> month(a) = month(a) +1
> a
[1] NA

For both the cases it should give "2013-05-28"

**Comment by vspinu** [comment]
This is not a bug. Read the documentation of `%m+%` and `Period-class`.

**Comment by vspinu** [comment]
To clarify a bit more. You are trying to convert `2013-05-31` to `2013-02-31` which does not exist. So it produces NA. Use `a %m-% months(3)` or `add_with_rollback` directly.

**Comment by vkvarjun** [comment]
Yeah, I got it with %m-%months(3). Also, I understood your explanantion. 
But thought if this {a = as.Date("2013-01-31") ; month(a) = month(a) +1} could also set "2013-05-28" as the value (for more flexibility). 
Anyways, Thank you so much for your response.
