### ISSUE TITLE
month division bug?

### ISSUE THREAD

**Issue by sean-violante-lendico** [hadley/lubridate#352]
for most of my dates everything works just not for this:

    interval(as.Date('2014-01-31'),as.Date('2015-09-01'))%/%months(1)

    Error in while (any(start + est * per < end)) est[start + est * per <  : 
     missing value where TRUE/FALSE needed

I am using lubridate 1.3.3

**Comment by vspinu** [comment]
This is fixed development version.

```
>     interval(as.Date('2014-01-31'),as.Date('2015-09-01'))%/%months(1)
[1] 19
```
