### ISSUE TITLE
Both parse_date_time and as.POSIXct  cannot parse ""01/01/2010 00:00:01 AM"

### ISSUE THREAD

**Issue by dracodoc** [hadley/lubridate#354]
I want to create a date time object as cut off reference point for all date time after 2010. So I tried to create it like this:

    > as.POSIXct("01/01/2010 00:00:01 AM", tz = "America/New_York", format = "%m/%d/%Y %I:%M:%S %p")
    [1] NA

`parse_date_time` have same result:

	> parse_date_time("01/01/2010 00:00:01 AM", "%m/%d/%Y %I:%M:%S %p",  tz = "America/New_York")
	[1] NA
	Warning message:
	All formats failed to parse. No formats found. 

I found they can deal with the string without AM/PM:

    > parse_date_time("01/01/2010 00:00:01", "%m/%d/%Y %H:%M:%S",  tz = "America/New_York")
    [1] "2010-01-01 00:00:01 EST"

and if the hour is at least 1:

    > parse_date_time("01/01/2010 01:00:01 AM", "%m/%d/%Y %I:%M:%S %p",  tz = "America/New_York")
    [1] "2010-01-01 01:00:01 EST"

Of course I can work around this by using the string without AM/PM or even ignore the time part only using date, but I felt the inconsistency here may implying some bugs.

**Comment by vspinu** [comment]
I think this is how `I` format works. It cannot take 00. your date is actually:

```
parse_date_time("01/01/2010 12:00:01 AM", "%m/%d/%Y %I:%M:%S %p",  tz = "America/New_York", locale = "en_US.utf8")
[1] "2010-01-01 00:00:01 EST"
```

BTW, just a  hint, you can use user friendly `dmy_hms` for this:

```
> dmy_hms("01/01/2010 00:00:01 PM", tz = "America/New_York")
[1] "2010-01-01 00:00:01 EST"
> dmy_hms("01/01/2010 4:00:01 PM", tz = "America/New_York")
[1] "2010-01-01 16:00:01 EST"
```

The reason it works with the first example is that it parses it with a different `H` format when it sees that `H` doesn't work.

**Comment by vspinu** [comment]
BTW, when I will port `I,p` formats to C I will allow `00` in there. I think it's intuitive and seems to be occurring in the real world out there.

**Comment by dracodoc** [comment]
I got it. It's the convention of using `12:00:01 AM` when using AM instead of `00:00:01 AM`. 

However I cannot make it parse `0` without AM/PM too:

	> parse_date_time("01/01/2010 0:00:01", "%m/%d/%Y %I:%M:%S",  tz = "America/New_York")
	[1] NA
	Warning message:
	All formats failed to parse. No formats found. 

I thought the document said

> I
Hours as decimal number (01–12 or 0–12).

Is there something wrong with my usage? or the `0-12` is not supposed to used like this?

I tried further:

	> parse_date_time("01/01/2010 0", "%m/%d/%Y %I",  tz = "America/New_York")
	[1] NA
	Warning message:
	All formats failed to parse. No formats found. 
	> parse_date_time("01/01/2010 1", "%m/%d/%Y %I",  tz = "America/New_York")
	[1] "2010-01-01 01:00:00 EST"

**Comment by vspinu** [comment]
> However I cannot make it parse 0 without AM/PM too:

It's an issue with `I` not with `p`.

>     Hours as decimal number (01–12 or 0–12).

Oh. This is a typo. It should be `1-12`. These stuff is exactly the same as with `strptime`. Fixing now.
