### ISSUE TITLE
lubridate fails to install or load in a path containing a colon ":"

### ISSUE THREAD

**Issue by cole-christensen** [hadley/lubridate#357]
test script: http://pastebin.com/xHN22iF6
Install output: http://pastebin.com/NjrvfVPb

For $reasons, I need to have R libraries installed in a directory which happens to have colons in it's name, most libraries do okay, lubridate doesn't. I've written test scripts above showing the important bits of replicating the error which does not occur if the directory name is "AB" instead of "A:B"

**Comment by vspinu** [comment]
You should see the same problem with all packages with compiled code.  Lubridate src is trivial. So it's either R's problem or gcc or who knows.

I cannot reproduce your problem on ubuntu with R 3.1.2. 

```
** package 'lubridate' successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG  "-I/home/vspinu/.lib/R/Rcpp/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c tparse.c -o tparse.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o lubridate.so tparse.o -L/usr/lib/R/lib -lR
installing to /home/vspinu/tmp/A:B/r-libs/lubridate/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Loading required package: grDevices
* DONE (lubridate)
```
