### ISSUE TITLE
Could `with_tz` take a vector of `tzones`?

### ISSUE THREAD

**Issue by josiekre** [hadley/lubridate#359]
I have a dataframe with a column of timestamps in UTC and another column with the local timezone. I need to create new columns such as:  the timestamp converted to the local time or the number of minutes since midnight in the local timezone. 

These variables are useful when looking at travel behavior. Working in relation to the local time zone rather than strictly using UTC is essential to the analysis.

Here is an example dataframe.
```{r}
library(dplyr)
data <- data_frame(
  timestamp_utc = as.POSIXct(c('2015-11-18 03:55:04', '2015-11-18 03:55:08', 
                    '2015-11-18 03:55:10'), tz = "UTC"),
  local_tz = c('America/New_York', 'America/Los_Angeles', 
               'America/Indiana/Indianapolis')
  )
````

I'd like to be able to use something like `with_tz`, but it doesn't work in a chain of other `dplyr` statements due to the fact that `tzone` cannot be a vector.
```{r}
mutate(data, timestamp_local = with_tz(timestamp_utc, tzone = local_tz))
```

I've created a work around, but it is slow (see [StackOverflow](http://stackoverflow.com/questions/33848563/with-tz-with-a-vector-of-timezones/33848764#33848764)). With this method, the result has to be a string, otherwise `unlist()` or `c()` will turn the result back to the system timezone, which in this case is UTC.
```{r}
get_local_time <- function(timestamp_utc, local_tz) {
  l <- lapply(seq(length(timestamp_utc)), function(x) {
    format(with_tz(timestamp_utc[x], local_tz[x]), "%FT%T%z")
  })
  unlist(l)
}

> mutate(data %>% timestamp_local = get_local_time(timestamp_utc, tzone = local_tz))
Source: local data frame [3 x 3]

        timestamp_utc                     local_tz          timestamp_local
               (time)                        (chr)                    (chr)
1 2015-11-18 03:55:04             America/New_York 2015-11-17T22:55:04-0500
2 2015-11-18 03:55:08          America/Los_Angeles 2015-11-17T19:55:08-0800
3 2015-11-18 03:55:10 America/Indiana/Indianapolis 2015-11-17T22:55:10-0500
```

Could `with_tz` take a vector of `tzones`?

**Comment by josiekre** [comment]
Update:

Using `dplyr::combine()` rather than `unlist()` allows the variable to remain date times rather than converting to strings, but the timezone attribute is still a single value rather than a vector.

```{r}
> get_local_time <- function(timestamp_utc, local_tz) {
    l <- lapply(seq(length(timestamp_utc)), 
                function(x) {with_tz(timestamp_utc[x], local_tz[x])})
    combine(l)
    }

> [x <- mutate(data, timestamp_local = get_local_time(timestamp_utc, tzone = local_tz))]

Source: local data frame [3 x 3]

        timestamp_utc                     local_tz     timestamp_local
               (time)                        (chr)              (time)
1 2015-11-18 03:55:04             America/New_York 2015-11-17T22:55:04
2 2015-11-18 03:55:08          America/Los_Angeles 2015-11-17T19:55:08
3 2015-11-18 03:55:10 America/Indiana/Indianapolis 2015-11-17T22:55:10

> attr(x$timestamp_local, "tone")
[1] "America/New_York"
```

**Comment by vspinu** [comment]
This is against core R. We cannot deal with a vector of timezones. A date-time vector must have same uniform time zone by construction. 

I also don't think it's "essential" to have different time zones for each value. It's the same time instance after all.

**Comment by tomkom** [comment]
I do not understand the last comment - why would the vector need to share a timezone. I have large amounts of worldwide migration data, each timestamped in a different timezone, not expressed in the timestamp itself. I found this discussion when looking for a solution to the inverse problem - converting all the timestamps from strings of local time to timezone enhanced data, and then all to UTC. What would be the preferred way of doing this, then?

**Comment by josiekre** [comment]
@tomkom Do you have the lat/lon for each timestamp? If so, I'd append on the timezone using sp::over and a timezone shapefile (e.g., http://efele.net/maps/tz/world/). Then you can back into UTC: Since you can't use lubridate to do this in a vectorized way, I would instead create a column that is the time offset as a signed 'int'. Then just reverse that from the timestamp to arrive at the UTC timestamp. This you can do fast with basic dplyr methods.

Do that make sense?

**Comment by josiekre** [comment]
I used the word "essential" because in the case I had at hand the local time was more important than the UTC time. In dealing with travel behavior data, we care more that someone left for work at 8am local time than we do that it was 2am UTC time. When the data are spread across different timezones, we still need to be able to figure out that local time. For example, do people in the suburbs of Seattle leave for work earlier in their morning than people in the suburbs of Atlanta? 

As an alternative solution to this, we created a column that was minutes from midnight local time. This removed the timezone vector problem described here in this issue.

**Comment by vspinu** [comment]
>  I found this discussion when looking for a solution to the inverse problem - converting all the timestamps from strings of local time to timezone enhanced data, and then all to UTC. What would be the preferred way of doing this, then? 

Currently there is no way to parse timezones. The best you can do is to extract your timezones with gsub or substr into a separate TZ column. Then group_by by that TZ collumn and `ymd_hms` with tz argument. Finally `with_tz` to UTC.  Two lines of code.

@josiekre, you answered your own question. If your analysis is about hours within a day, then you should probably work with a separate variable of the HH:MM:SS of that day. 

Alternatively, work with UTC and keep in mind that those are local times. This "solution" will ignore DTS shifts, but it looks like for your purpose that's not a problem.  It will also not work when same entity has record in several timezones.

**Comment by Harish2f** [comment]
> Update:
> 
> Using `dplyr::combine()` rather than `unlist()` allows the variable to remain date times rather than converting to strings, but the timezone attribute is still a single value rather than a vector.
> 
> ```r
> > get_local_time <- function(timestamp_utc, local_tz) {
>     l <- lapply(seq(length(timestamp_utc)), 
>                 function(x) {with_tz(timestamp_utc[x], local_tz[x])})
>     combine(l)
>     }
> 
> > (x <- mutate(data, timestamp_local = get_local_time(timestamp_utc, tzone = local_tz)))
> 
> Source: local data frame [3 x 3]
> 
>         timestamp_utc                     local_tz     timestamp_local
>                (time)                        (chr)              (time)
> 1 2015-11-18 03:55:04             America/New_York 2015-11-17T22:55:04
> 2 2015-11-18 03:55:08          America/Los_Angeles 2015-11-17T19:55:08
> 3 2015-11-18 03:55:10 America/Indiana/Indianapolis 2015-11-17T22:55:10
> 
> > attr(x$timestamp_local, "tzone")
> [1] "America/New_York"
> ```

**Comment by Harish2f** [comment]
Isn't working for me :-(
Error in get_local_time(Closed, tzone = `Time zone`) : 
  unused argument (tzone = `Time zone`)
