### ISSUE TITLE
Efficient instant creation functions

### ISSUE THREAD

**Issue by hadley** [hadley/lubridate#365]
i.e. if I have year, month, and day, how do I efficiently create a date (or date time)?

**Comment by vspinu** [comment]
`ISOdate` and `ISOdatetime` is what you are looking for. Not the most user friendly names though.

**Comment by vspinu** [comment]
How about renaming them into `make_date` and `make_datetime`? We already have `make_difftime` to overcome the existent `base::difftime` constructor. 

Even better, we can use `date` and `datetime` and fall back to `base::date` when the function is called with no arguments.

**Comment by hadley** [comment]
Sorry, the key was "efficient" - `ISOdatetime()` works by pasting together the values and then parsing. That's clearly a suboptimal approach. I like `make_datetime()`, but I think they should raise an error when called without arguments (since we already have `now()` and it's better for each function to do one job well)

**Comment by vspinu** [comment]
> the key was "efficient" - ISOdatetime()

That's pretty efficient. Any other operation with dates will likely be much more time consuming. We can think of implementing it from scratch but I would like to see a use case when the current situation would be a bottleneck and the speed improvements would actually matter. 

(somewhat related #324)

**Comment by hadley** [comment]
I'd say ISODateTime is at least 100x slower than it could be. It's definitely a problem when you're working with data frame with millions of row.

We could do this much more efficiently in C.

**Comment by vspinu** [comment]
> I'd say ISODateTime is at least 100x slower than it could be.

Oh. You are right. I was confused. I though that ISOdate and ISOdatetime are our functions and they are based on our C parser. 

Indeed, they are very slow and I actually replaced myself all occurrences of ISOdatetime in our code a year or so ago. We already can get 100x speedup with our fast_strptime function.

**Comment by hadley** [comment]
Yeah, and it should be even faster if we don't paste and parse and instead creating the time object in C directly.

**Comment by vspinu** [comment]
Hm. I have added `fast_datetime`. Unfortunately pasting takes 99.9% of the time so it's not a great improvement overall. I am afraid we will have to do it directly.

**Comment by vspinu** [comment]
I have ported `make_datetime` to C. it resulted in 100x speedup indeed.

**Comment by hadley** [comment]
Nice!
