### ISSUE TITLE
Use another locale parse_date_time()?

### ISSUE THREAD

**Issue by Deleetdk** [hadley/lubridate#366]
[Question on SO](http://stackoverflow.com/questions/34375758/date-recognition-fails-with-strptime-and-parse-date-time-dont-know-why).

I had an odd error about:

```
parse_date_time("31/Dec/2012:06:20:10", orders = "dbYHMS")
parse_date_time("01/May/2013:00:01:37", orders = "dbYHMS")
```

The first works fine, the second returns NA. I could not find the problem. Eventually, I tried all the months and noticed that "Oct" also does not work. Then I realized what the problem was: it uses the system locale on default which is Danish, not English (for me). The abbreviations for these two months are different ("May" vs. "Maj", and "Oct" vs. "Okt"), but the rest just happen to match the English ones.

I searched and cannot find a way to change the locale for parsing times. Is it possible? I tried:

```
> Sys.getlocale(category = "LC_ALL")
[1] "LC_COLLATE=Danish_Denmark.1252;LC_CTYPE=Danish_Denmark.1252;LC_MONETARY=Danish_Denmark.1252;LC_NUMERIC=C;LC_TIME=Danish_Denmark.1252"
```

Which seems to show that no other locales are available. Not sure how to proceed from here.

As a workaround, one can replace the month names first, but it is not a good solution.

**Comment by vspinu** [comment]
Sorry for the late reply. I am traveling with limited connectivity. 

Almost all `lubridate` parsing functions have argument `locale` which you should set to an English locale before parsing English dates. In the future all English datetimes will be parsed automatically (#287 is the key here).

With `Sys.setlocale` you can alter the value of `LC_TIME` locale per R session. On unix-like systems you should be able to see all installed locales on your system with `locale -a`.

**Comment by Deleetdk** [comment]
Could you tell me how to do that? I was unable to discover how to do it by reading the documentation. It just points to `locale()` which was not helpful to me. An example would be nice, since this is a common problem.

**Comment by vspinu** [comment]
On my machine this is the list of available locales:

```
~$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
it_CH.utf8
it_IT.utf8
nl_NL.utf8
POSIX
zh_CN.utf8
zh_HK.utf8
zh_SG.utf8
zh_TW.utf8
```
Thus I can pick any of those locales and use as an argument to any of the lubridate parsing functions. For example:

```
> dmy_hms("31/Dec/2012:06:20:10", locale = "en_US.utf8")
[1] "2012-12-31 06:20:10 UTC"
```

**Comment by vspinu** [comment]
For completeness, this is how you change it per session:

```
Sys.setlocale(category = "LC_TIME", locale = "en_US.utf8")
```

As I said earlier, this awkwardness won't be necessary in the near future for english locales.

**Comment by Deleetdk** [comment]
It is not possible to use a custom locale on my machine. Winders problems, presumably:

```
Warning messages:
1: In Sys.setlocale("LC_TIME", locale) :
  OS reports request to set locale to "en_US.utf8" cannot be honored
2:  38 failed to parse. 
```

So I still have to replace month names with their local versions. Annoying because it means that my code is not reproducible on other machines!

**Comment by vspinu** [comment]
> It is not possible to use a custom locale on my machine. Winders problems, presumably:

It should be possible. It's just named differently on windows. Search the net. Maybe `"English_United States.1252"`.

**Comment by Deleetdk** [comment]
That worked. Not sure where you found that code tho.
