### ISSUE TITLE
Possible "week" bug?

### ISSUE THREAD

**Issue by Ironholds** [hadley/lubridate#368]
According to the documentation "[week] returns the week as it would appear in the ISO 8601 system"

    > week(as.Date("2015-11-23")) # Monday
    [1] 47
    > week(as.Date("2015-11-24")) # Tuesday
    [1] 47
    > week(as.Date("2015-11-25")) # ..Wednesday
    [1] 48

Every other ISO8601 thing I've found to test against thinks the 23rd is in week 48. Any idea what's going on?

**Comment by vspinu** [comment]
What documentation are you looking at?

In [current version](https://github.com/hadley/lubridate/blob/master/R/accessors-week.r#L10) it says `‘isoweek returns the week as it would appear in the ISO 8601`. 

`week` is a rather brute computation of the number of 7day intervals since the begining of the year.

**Comment by Ironholds** [comment]
The same documentation you're looking at, which is why what I quoted lines up almost perfectly (absent inserts) with what you said.

Yes, I know that it's a brute computation; I read the documentation which is how I could quote it. But it's a brute computation that does not agree with any other brute computation. It is putting 23 November in week 47.

1. [week 48](http://www.epochconverter.com/date-and-time/weeknumbers-by-year.php)
1. [week 48](http://www.timeanddate.com/calendar/?country=21)
1. [week 48](http://planetcalc.com/1252/)

**Comment by vspinu** [comment]
`isoweek` gives 48 as expected. I will check this out manually in the evening.

**Comment by Ironholds** [comment]
Awesome; thank you. It may simply be a case of documentation improvements (week and isoweek documented on the same page is pretty confusing if they do different things).

**Comment by vspinu** [comment]
All your examples point to ISO weeks. I have clarified the documentation. It now says:

```
     ‘week’ returns the number of complete seven day periods that have
     occured between the date and January 1st, plus one.

     ‘isoweek’ returns the week as it would appear in the ISO 8601
     system, which uses a reoccuring leap week.
```

**Comment by Ironholds** [comment]
Perfect; thanks!
