### ISSUE TITLE
as.period(interval(...)) off by a month

### ISSUE THREAD

**Issue by tjmahr** [hadley/lubridate#371]
```r
packageVersion("lubridate")
#> [1] ‘1.5.0’

t1 <- "1985-11-24"
t2 <- "2007-08-13"
as.period(interval(t1, t2))
#> [1] "21y 9m 19d 23H 0M 0S"
```
But the amount of time between the two dates is [21 years, 8 months, 20 days](http://www.wolframalpha.com/input/?i=1985-11-24+to+2007-08-13).

**Comment by vspinu** [comment]
This is a bug. Wrong computation with months.I am a bit surprised this went though unnoticed in our tests.
