### ISSUE TITLE
vector of dates -- is this normal behaviour of dates?

### ISSUE THREAD

**Issue by masalmon** [hadley/lubridate#372]
``` r
data.frame(time=ymd_hms("2013-10-30 12:49:10"))
data.frame(time=c(ymd_hms("2013-10-30 12:49:10"), ymd_hms("2013-10-30 12:49:10")))
lala <- data.frame(time=ymd_hms("2013-10-30 12:49:10"))
rbind(lala, lala)
``` 

I'm wondering why the second line gives me different times. Why is the timezone lost when using c()?

**Comment by vspinu** [comment]
You haven't provided the output. 

`c` resets the timezone to your current timezone. This is how R works. Lubridate tries to work with UTC as much as it can. It's the same time instant, so should not create problems with time manipulation:

```
> c(ymd_hms("2013-10-30 12:49:10"))
[1] "2013-10-30 13:49:10 CET"
> ymd_hms("2013-10-30 12:49:10")
[1] "2013-10-30 12:49:10 UTC"
> 

````

**Comment by masalmon** [comment]
ok thanks a lot!
