### ISSUE TITLE
missing `date` function

### ISSUE THREAD

**Issue by joethorley** [hadley/lubridate#373]
lubridate provides `day`, `hour` and `year` functions to get and set the day, hour and year components of a date time. A logical addition would be a `date` function to get and set the date component. It would circumvent the use of as.Date(,tz) which can cause problems if tz is set wrong. It would conflict with the base version of `date` which is poorly named and effectively replaced by lubridate::today. It could be called `d8` to avoid any conflicts. 

Please let me know if I am missing something.

I am willing to implement.

**Comment by vspinu** [comment]
Closely related to #355. 

I would call it  `date` for the sake of consistency. Users of lubridate are very unlikely to use `base::date` anyways.

@hadley, @huftis, what do you think?

**Comment by hadley** [comment]
Hmmm, I'm not a big fan of overriding base R functions (although I agree it wouldn't make much difference here). Why not call it `make_date()` to be consistent with `make_datetime()`?

**Comment by vspinu** [comment]
> Why not call it make_date() to be consistent with make_datetime()?

`make_datetime` is a constructor. The proposal is to add a "getter" and "setter"  for date. That is, to extend the existent family of our accessors -`year`, `day`, `month` etc.

**Comment by joethorley** [comment]
`get_date` and `set_date` could work?

**Comment by hadley** [comment]
Ooooh, I totally misread that

**Comment by joethorley** [comment]
Unless someone tells me otherwise I'm going to do a pull request early next week for `get_date` and `set_date`

**Comment by vspinu** [comment]
`get_date` and `set_date` is pretty bad IMO. It conflicts with R's `foo<-` convention and makes our accessors heterogeneous, which I don't like at all. 

Overwriting `date` is a small price  to pay for clarity and consistency of `date(x)` and `date(x) <- d`.  Let's just go with overwrite for now and change it in a later stage if we happen to have a better idea.

**Comment by joethorley** [comment]
Agreed - I'll implement early next week

Sent from my iPhone

On Jan 22, 2016, at 22:02, Vitalie Spinu <notifications@github.com> wrote:

get_date and set_date is pretty bad IMO. It conflicts with R's foo<-
convention and makes our accessors heterogeneous, which I don't like at
all.

Overwriting date is a small price to pay for clarity and consistency of
date(x) and date(x) <- d. Let's just go with overwrite for now and change
it in a later stage if we happen to have a better idea.

—
Reply to this email directly or view it on GitHub
<https://github.com/hadley/lubridate/issues/373#issuecomment-174152431>.
