### ISSUE TITLE
Messy NEWS

### ISSUE THREAD

**Issue by Ironholds** [hadley/lubridate#374]
https://cran.rstudio.com/web/packages/lubridate/news.html is extremely messy for me, because of...something.

Any chance it could be switched out for a plain ol' NEWS file? Not only would this not result in formatting problems, it'd be grabbable from the RStudio updates pane.

**Comment by vspinu** [comment]
News.md is a clean [text file](https://github.com/hadley/lubridate/blob/master/NEWS.md). I guess it's a question for R folks what are they using to convert .md to html. 

@hadley, any ideas of how to fix this? Otherwise I will report an R bug. Using markdown for news file is a standard practice.

**Comment by Ironholds** [comment]
Well, I see problems rendering it with the RStudio preview, so it's not just whatever CRAN is using. It looks like the problem is the ------ above titles; it's reading everything as a title and ignoring the markup below it.
