### ISSUE TITLE
Leap year oddity (?) with `years` and `months`

### ISSUE THREAD

**Issue by waynefoltaERI** [hadley/lubridate#384]
This was executed today (Feb 29, 2016):

> now() - years(1)
[1] NA
> now() - months(12)
[1] NA
> now() - days(365)
[1] "2015-03-01 14:40:52 EST"
> now() - years(4)
[1] "2012-02-29 14:41:11 EST"

It's tricky to decide what this should do, but it seems like `NA` is unexpected.

**Comment by Titolondon** [comment]
It think that this behavior is by designed for consistency. You could find some explanation in the [lubridate vignette](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html) about date arithmetic and leap year. It says 
> if adding or subtracting a month or a year creates an invalid date, lubridate will return an NA.

Depending of what you want, you could do something like
```r
date <- ymd("2016-02-29")
date - years(1)
[1] NA
date %m-% years(1)
[1] "2015-02-28 UTC"
date %m+% years(-1)
[1] "2015-02-28 UTC"
add_with_rollback(date, years(-1), roll_to_first = TRUE)
[1] "2015-03-01 UTC"
```
see help page for [%m+%](http://rpackages.ianhowson.com/cran/lubridate/man/mplus.html)

**Comment by waynefoltaERI** [comment]
Thanks! I'd suggest that a sentence or two be added to the `years` and `months` documentation to note this. Vignettes are sort of a secondary source, and I wasn't aware of `%m+%` page -- is it a relatively new function?

**Comment by vspinu** [comment]
This is documented in a couple of places, most notably in `period-class`:

```

     The logic that guides arithmetic with periods can be unintuitive.
     Starting with version 1.3.0, lubridate enforces the reversible
     property of arithmetic (e.g. a date + period - period = date) by
     returning an NA if you create an implausible date by adding
     periods with months or years units to a date. For example, adding
     one month to January 31st, 2013 results in February 31st, 2013,
     which is not a real date. lubridate users have argued in the past
     that February 31st, 2013 should be rolled over to March 3rd, 2013
     or rolled back to February 28, 2013. However, each of these
     corrections would destroy the reversibility of addition (Mar 3 -
     one month == Feb 3 != Jan 31, Feb 28 - one month == Jan 28 != Jan
     31). If you would like to add and subtract months in a way that
     rolls the results back to the last day of a month (when
     appropriate) use the special operators, ‘%m+%’, ‘%m-%’ or a bit
     more flexible ‘add_with_rollback’.
```
This is probably most unexpected behavior for new users and I agree that this should be referenced in a couple of more places.  I am fixing that.
I am making an effort to

**Comment by waynefoltaERI** [comment]
Got a good answer, thanks! (It was rather fun to discover a bug that took place on leap year day.)

This is documented under `period-class`, in some detail. I missed that. Was told that a couple more mentions will be made elsewhere, so closing this out.
