### ISSUE TITLE
ceiling_date behavior should fit the intuition at boundary

### ISSUE THREAD

**Issue by shrektan** [hadley/lubridate#390]
### Issue Description

As discussed in #262, the `ceiling_date` behaves strangely at the boundary (i.e., the first date of a month or a quarter), as documented in `ceiling_date`,

> By convention the boundary for a month is the first second of the month. Thus floor_date(ymd("2000-03-01"), "month") gives "2000-03-01 UTC".

### Current behavior

```r
lubridate::ceiling_date(as.Date("2016-03-01"), unit = "month")
# [1] "2016-03-01"
lubridate::ceiling_date(as.Date("2016-03-02"), unit = "month")
# [1] "2016-04-01"
```

### What users might expect 

However, the users (at least myself) would naturally expect the two lines above return the same value `2016-04-01`.

**Comment by vspinu** [comment]
One solution would be to define boundary for all units being uniformly `00` not `00` for some (hour, minute, second) and `01` for others (day, month). In that case `yyyy-04-01` will be ceiled to `yyyy-05-01`. 

This would mean that day and month don't have a boundary which implies at least two bad things. First one being that `floor(ceiling(...)` is not the same as `floor`, second is that `ceiling(ceiling(...))` for a date jumps over two months. This is a major change and might break current code in quite unexpected ways. 

So I am thinking to add a new argument to `ceiling_date`. Maybe `ceiling_on_1` or `no_boundary`? Other ideas? If, TRUE, ceiling behaves as you propose. If FALSE, it's the current behavior. This might be a global option which you can set with `options` once per session.

**Comment by vspinu** [comment]
I have settled on `change_on_boundary` (defaults to FALSE). Please let me know if you think the argument name can be better. Thanks.

**Comment by shrektan** [comment]
@vspinu Thanks. Naming is really hard... I think `change_on_boundary` is very clear for me, but if I can come up with something more concise I'll let you know :smiley:

**Comment by mr-teu** [comment]
Thanks, ran into this issue literally 5 minutes ago!

**Comment by vspinu** [comment]
Just letting you guys know that there is no global option for `change_on_boundary` anymore. See #443 for the reference. Just make a wrapper function if you are bothered by typing the option every time.
