### ISSUE TITLE
fast_strptime differs from strptime in regards to tz parameter

### ISSUE THREAD

**Issue by trittweiler** [hadley/lubridate#394]
It seems that fast_strptime considers the input string to be specified in GMT and uses its `tz` argument to bring the specified time relative to the timezone of the tz argument.

```
> "12/03/16 12:00" %>% strptime("%d/%m/%y %H:%M", tz="Europe/Zurich")
[1] "2016-03-12 12:00:00 CET"
```

versus

```
> "12/03/16 12:00" %>% fast_strptime("%d/%m/%y %H:%M", tz="Europe/Zurich")
[1] "2016-03-12 13:00:00 CET"
```

I am running R 3.2.3 and lubridate 1.5.0.

**Comment by vspinu** [comment]
This is a bug. Looking into it right now. Thanks.
