### ISSUE TITLE
Bug? Trying to add years to a date.

### ISSUE THREAD

**Issue by Make42** [hadley/lubridate#404]
I am running Kubuntu 14.4, lubridate 1.5.6 and this is not quite as I hoped (and the first line is from the manual!)

    > ymd(20120101) + years(1)
    # ERROR: ... because ymd(20120101) is of `Date`
    > as.POSIXct(ymd(20120101)) + years(1)
    # ERROR: ... because ymd(20120101) is of `POSIXt`
    > ymd(20120101) + dyears(1)
    [1] "88354-08-21"
    > as.POSIXct(ymd("20120101")) + dyears(1)
    [1] "2012-12-31 01:00:00 CET"

**Comment by vspinu** [comment]
Strange. It works just fine for me:

```
> ymd(20120101) + years(1)
[1] "2013-01-01"
> 
```

Kubuntu 15.10 here, but very recent R. What version of R do you see?

Can you send the full backtrace?

**Comment by Make42** [comment]
R is 3.2.4. How do I output the full backtrace?

**Comment by vspinu** [comment]
It's same version as mine. Can you reinstall lubridate and try again?

> How do I output the full backtrace?

```
traceback()
```

**Comment by Make42** [comment]
The miracle of R... after the reboot of the machine, everything works as it should... :-( Well at least that is resolved :+1:
