### ISSUE TITLE
Calling lubridate function produces error after repeated detaching and loading lubridate, plyr and dplyr

### ISSUE THREAD

**Issue by wooded** [hadley/lubridate#406]
A few days ago I was running in R script in RStudio that loaded a number of packages, then detached them before finishing. After a point, I would receive the following error when calling ymd():

    Error in .Call("parse_dt", x, format, TRUE, FALSE) : 
    "parse_dt" not resolved from current namespace (lubridate)

Yesterday I found the following question on SO.
http://stackoverflow.com/questions/20984833/parse-dt-not-resolved-from-current-namespace-lubridate/36886329#36886329

The answer provided a working example that replicates the error every time.

    ## LOAD PACKAGES
    library(plyr) # Important to load plyr before dplyr due to function masking.
    library(dplyr)
    library(lubridate)
    
    dateTemp <- mdy("01-01-1910")
    
    ## Cleanup
    pkgs <- names(sessionInfo()$otherPkgs)
    pkgs <- paste('package:', pkgs, sep = "")
    lapply(pkgs, detach, character.only = TRUE, unload = TRUE, force = TRUE)

The second time I source this file in an R session, the error occurs. 

I have updated RStudio, R and the packages involved to the latest version. The error is reproduced in RStudio and R.

Here is my sessionInfo() after first execution of the file:

    R version 3.2.4 (2016-03-10)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.10.5 (Yosemite)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    loaded via a namespace (and not attached):
     [1] magrittr_1.5    R6_2.1.2        assertthat_0.1  parallel_3.2.4 
     [5] tools_3.2.4     DBI_0.3.1       Rcpp_0.12.4     lubridate_1.5.6
     [9] stringi_1.0-1   stringr_1.0.0  

And at the time of the error message:

    R version 3.2.4 (2016-03-10)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.10.5 (Yosemite)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] lubridate_1.5.6 dplyr_0.4.3     plyr_1.8.3     
    
    loaded via a namespace (and not attached):
    [1] magrittr_1.5   R6_2.1.2       assertthat_0.1 parallel_3.2.4 tools_3.2.4   
    [6] DBI_0.3.1      Rcpp_0.12.4    stringi_1.0-1  stringr_1.0.0 

Perhaps unrelated, I found mention of the error message in an Issue for the dplyr repository.
https://github.com/hadley/dplyr/issues/750#issuecomment-65524937

**Comment by vspinu** [comment]
I cannot reproduce this on linux. I guess it's something mac related. But, do plyr and dplyr have anything to do with it? Or you can reproduce this error just with lubridate?

**Comment by wooded** [comment]
I've run through all sixteen permutations of lubridate, plyr/lubridate, dplyr/lubridate, plyr/dplyr/lubridate on first and second source() of the file. After each trial, I quit the R session and restarted before continuing to the next trial.

The following combinations lead to the error message consistently. 
<list of packages loaded on 1st source() of file> -> <list on 2nd source() of file>

The following five combinations produced the error 100% of the time.
plyr/lubridate -> plyr/lubridate
plyr/lubridate -> dplyr/lubridate
plyr/lubridate -> plyr/dplyr/lubridate

plyr/dplyr/lubridate -> plyr/lubridate
plyr/dplyr/lubridate -> plyr/dplyr/lubridate

The error seemed to pop up every day or two in the project I'm working on. This series of tests, though, yielded 100% reproducibility on my machine. I hope this helps.

**Comment by vspinu** [comment]
Ok. Now I can reproduce. The key he is the "source for the second time" and it is not occurring with plyr or dplyr only. It occurs with other packages I have tried.  It's very likely an R bug and should be reported accordingly. 

This is the content of tmp.R:

```
library(MASS)
library(lubridate)

mdy("01-01-1910")

## Cleanup
pkgs <- names(sessionInfo()$otherPkgs)
pkgs <- paste('package:', pkgs, sep = "")
lapply(pkgs, detach, character.only = TRUE, unload = TRUE, force = TRUE)
```

Then I do `source("./tmp.R");source("./tmp.R")` and get 

```
Error in .Call("parse_dt", x, format, TRUE, FALSE) (from parse.r#609) : 
  "parse_dt" not resolved from current namespace (lubridate)
```
 on the second `source`.

**Comment by hadley** [comment]
You really shouldn't expect `detach()` to work in this way. It's much better to restart R to get a clean session.

**Comment by EdwinTh** [comment]
I do get the same error when loading lubridate via a source scripts in the unit tests of [my package](https://github.com/EdwinTh/padr/tree/master/tests/testthat). I can run the unit tests only once per R session, I have to restart the session each time I want to run my unit tests. I do not (actively) detach the package. Are you sure it is an R bug, since lubridate is the only package I have experienced this with?

**Comment by vspinu** [comment]
> Are you sure it is an R bug, since lubridate is the only package I have experienced this with?

I see no reason why it should be specific to lubridate.  Same problem should occur with all packages that use dynamic libraries (have `useDynLib` in their NAMESPACE).

**Comment by EdwinTh** [comment]
Ok, than it is a coincidence that lubridate is the only package with a dynamic libraries that I use in this way. Thanks
