### ISSUE TITLE
ceiling_date(date, "month") not working for first of month

### ISSUE THREAD

**Issue by FlorianWanders** [hadley/lubridate#408]
`ceiling_date(date, 'month')` correctly returns the first date of the next month, except when `date` is the first of the month. E.g.,  `ceiling_date(dmy("02.04.2016"), 'month')` correctly returns `2016-05-01`, but 
 `ceiling_date(dmy("01.04.2016"), 'month')` returns `2016-04-01`. 

This means that the function `last_day()` provided on the [lubridate vignette](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html) is not working when the date is the first of a month:

`
last_day <- function(date) {
        ceiling_date(date, "month") - days(1)
}
`

`last_day(dmy("02.04.2016"))` returns `2016-04-30` but `last_day(dmy("01.04.2016"))` returns `2016-03-31`

**Comment by shrektan** [comment]
Are you sure you tried the dev version? I think it has been fixed. 


发自网易邮箱大师
在2016年04月29日 23:27，FlorianWanders 写道:

ceiling_date(date, 'month') correctly returns the first date of the next month, except when date is the first of the month. E.g., ceiling_date(dmy("02.04.2016"), 'month') correctly returns 2016-05-01, but
ceiling_date(dmy("01.04.2016"), 'month') returns 2016-04-01.

This means that the function last_day() provided on the lubridate vignette is not working when the date is the first of a month:


last_day <- function(date) {
ceiling_date(date, "month") - days(1)
}


last_day(dmy("02.04.2016")) returns 2016-04-30 but last_day(dmy("01.04.2016")) returns 2016-03-31

**Comment by FlorianWanders** [comment]
Good point, apologies!

**Comment by vspinu** [comment]
This is by design. First day is a boundary and floor and ceiling return the boundary. By `fixed` @shrektan probably meant a new argument to `ceiling_date` `change_on_boundary`:

```
> ceiling_date(dmy("01.04.2016"), 'month', change_on_boundary = T)
[1] "2016-05-01"
```

See #390 for the reference. 

You can set the global option as well:

```
> options(lubridate.ceiling_date.change_on_boundary = TRUE)
> ceiling_date(dmy("01.04.2016"), 'month')
[1] "2016-05-01"
```
