### ISSUE TITLE
inconsistent argument names tz vs tzone

### ISSUE THREAD

**Issue by RoyalTS** [hadley/lubridate#416]
Perhaps there is some deeper logic to this but I find it confusing that the argument that specifies which timezone is to be used is named `tzone` for `with_tz()`, `force_tz()` but `tz` for `ymd()` and friends. Couldn't this be harmonized?

**Comment by vspinu** [comment]
You can always rely on partial matching and use `tz` throughout. I am afraid it's too late for shortening the tzone argument. While we can rename all `tz` into `tzone` and preserve compatibility, I very much prefer `tz` to `tzone`. Also R core functions tend to use `tz`.
