### ISSUE TITLE
Date parsers are failing with dates which are in 24:00 format

### ISSUE THREAD

**Issue by skgrange** [hadley/lubridate#418]
Hello lubridate team,
After the last update (version 1.5.6), the `parse_date_time` and `ymd_h*` functions fail to parse dates when the hour format includes the somewhat special case of 24 hours. The help file of the function still states that hours can take the form 0--24 and `strftime` performs as expected. An example: 

```
library(lubridate)

# An example
date_string <- "2016-05-24 24:00:00"

# Both cases fail
ymd_hms(date_string, tz = "UTC")
parse_date_time(date_string, orders = "ymd hms", tz = "UTC")

# Works correctly, first instant of next day
strftime(date_string, tz = "UTC")
```

Is this a deliberate regression? Many thanks.

**Comment by jstaf** [comment]
Can confirm this bug. I feel like lubridate should be able to handle this:
```
> ymd_hm("2016-05-27 24:00")
[1] NA
Warning message:
All formats failed to parse. No formats found. 
```

Meanwhile, strptime/strftime works just fine:

```
> strptime("2016-05-27 24:00", format = "%Y-%m-%d %H:%M")
[1] "2016-05-28 EDT"
```
