### ISSUE TITLE
Error in .Call(C_stri_sub_replacement,...) - incompatibility with the newest stringi Version?

### ISSUE THREAD

**Issue by ckluss** [hadley/lubridate#419]
Hi

there seems to be an incompatibility with the newest "gagolews/stringi" Version?

devtools::install_github("gagolews/stringi") # or install.library(stringi) from CTAN
devtools::install_github("hadley/stringr")
devtools::install_github("hadley/lubridate")

library(lubridate)
ymd(20090101)

Error in .Call(C_stri_sub_replacement, str, from, to, NULL, omit_na, value) : 
  Incorrect number of arguments (6), expecting 5 for 'C_stri_sub_replacement'

stringi version 1.1.1
lubridate version 1.5.6.9000

Best wishes
Christof

**Comment by ckluss** [comment]
devtools::install_version('stringi', version='1.0-1')

helps for the moment, but is no real solution, of course ;)

**Comment by vspinu** [comment]
I cannot reproduce this. Either it was fixed upstream or something went wrong on your side during installation. In any case, it's unlikely  be lubridate problem but  rather stringr or stringi. Please reinstall and re-open the issue if you still see the problem. Also provide a full backtrace in order for us to see where exactly the problem occurs. Thanks.
