### ISSUE TITLE
ceiling_date gives behaves differently before/after 1970

### ISSUE THREAD

**Issue by TonyLadson** [hadley/lubridate#421]
The result for ceiling_date for 1 Jan 1970 is 1 Jan 1971 as expected.  The result for all first Jan after 1970 just returns 1 Jan of that year:

`ceiling_date(ymd("1970-01-01"), "year") # [1] "1971-01-01"  `
`ceiling_date(ymd("1971-01-01"), "year") #[1] "1971-01-01"`

**Comment by vspinu** [comment]
I cannot see this. You are probably on a old version of lubirdate.

```R
> ceiling_date(ymd("1970-01-01"), "year")
[1] "1970-01-01"
> ceiling_date(ymd("1970-01-01"), "year", change_on_boundary = T)
[1] "1971-01-01"
```

Please upgrade and re-open the issue  if you still see the problem.  Thanks.
