### ISSUE TITLE
ymd() returns Date instead of POSIXct - please keep API stable (backward compatible)

### ISSUE THREAD

**Issue by aryoda** [hadley/lubridate#423]
Dear lubridate team,

the most recent update of lubridate to version 1.5.6 introduced a problem to ymd() by implementing the feature request [ Should ymd() and similar return a date? #391 ](https://github.com/hadley/lubridate/issues/391).

Before:
```
> class(ymd("1980-01-01"))
[1] "POSIXct" "POSIXt"
```

After update to lubridate 1.5.6:
```
> class(ymd("1980-01-01"))
[1] "Date"
```

**Therefore existing code breaks if it relies on POSIXct as class of the return value.**

Can you please fix this problem by
  1. switching back to POSIXct or
  2. introduce a new function like "ymd_POSIXct" that behaves like before for a simple migration of existing code by search&replace or
  3. adding an additional parameter to ymd() specifying the return type or
  4. add a new R option that can be configured globally to switch this behaviour.

**Generally I would suggest to not change the signature of a function any-more if it has been released.**

You could add a new function instead (e. g. "ymd2") like you can observe it sometime in the Windows C API.

PS: The documentation is also wrong now (still mentions POSIXct as return type): I will file a separate issue for this

**Comment by vspinu** [comment]
You can pass `tz="UTC"` to get the POSIXct.

**Comment by aryoda** [comment]
Yes, thx!

Adding the time zone is a valid workaround (but still requires more complicated code changes the simple search&replace).

**Comment by stevencb** [comment]
I agree with aryoda, `ymd` has been returning `"POSIXct" "POSIXt"` for a long time, and this can break a number of things in existing code that rely on this type (e.g. when using `scale_*_datetime` I get an error).  Would it make more sense to default it to what it was, but provide an option to have it return a date (i.e. for backward compatibility) ?

**Comment by vspinu** [comment]
The change has been there for a while. I expect most of the packages and custom code has been adjusted already. So, no. There will be no reversion. 

What is the problem with scale_*_date time? Please report on ggplot and mention this change.

**Comment by aryoda** [comment]
> what is the problem with ...

The underlying problem is the fundamental difference of the semantics:
```

d1 <- as.Date("2010/01/01")   # Dates are represented as the number of days since 1970-01-01
p1 <- as.POSIXct(d2)          # Class "POSIXct" represents the (signed) number of seconds since the beginning of 1970 (in the UTC time zone)

d1 + 10  # plus 10 days
# [1] "2010-01-11"

p1 + 10  # plus 10 seconds
# [1] "2011-01-01 01:00:10 CET"
```

Now imagine you do an `update.package` and do not know about the semantical change (`Date` instead of `POSIXct` as return type now).

Your date/time calculations would result in completely different results without getting an error/exception.

If the above code was part of a sophisticated stock exchange banking system you'd have the best chances to inscribe your name into every history book for the **big stock exchange crash in July 2016** (this is really just a joke :-)))

**Comment by vspinu** [comment]
> The underlying problem is the fundamental difference of the semantics:

That is understandable and nothing we can do about it. The decision has been made and reversal would cause even more pain than the transition already caused.  

I can add global setting for `tz` argument in `ymd` to allow for global "reversal" to previous behavior.

**Comment by aryoda** [comment]
I fully agree that undoing the change again would cause a lot of pain too.

That's why I suggested three more alternatives in my original post above.
Adding a "global setting" seems to implement one of my suggestions and is very welcome!

And please let me emphasize that I really appreciate the work you (and all the others) do here!

**Comment by stevencb** [comment]
I also agree, the work you and others do here is outstanding and much appreciated!

I believe the "scale_*_datetime" was brought up in another issue.  It is basically about giving an error when given a Date instead of a Posix.  I will have a look at that to see where things stand.

Thanks again.

**Comment by vspinu** [comment]
I have just made POSIX and Date comparable. POSIX and Date objects should be pretty much interchangeable now. 

Please report if you see other issues regarding POSIX and Date compatibility. Thanks.
