### ISSUE TITLE
ymd() returns Date instead of POSIXct - documentation not yet updated

### ISSUE THREAD

**Issue by aryoda** [hadley/lubridate#424]
Dear lubridate team,

the most recent update of lubridate to version 1.5.6 introduced a problem to ymd() by implementing the feature request [ Should ymd() and similar return a date? #391 ](https://github.com/hadley/lubridate/issues/391).

Before:
```
> class(ymd("1980-01-01"))
[1] "POSIXct" "POSIXt"
```

After update to lubridate 1.5.6:
```
> class(ymd("1980-01-01"))
[1] "Date"
```

The documentation of version 1.5.6 still says that ymd() "transforms... to POSIXct objects."

**Comment by vspinu** [comment]
Thanks for spotting this. The `tz` argument documentation was correct though.

**Comment by aryoda** [comment]
Yes, `tz` arg doc and the "Value" section were correct!
