### ISSUE TITLE
Problems with 31/30/28days long months [e.g. `dmy("31/05/2016")  - months(3) = NA`, expected "01/03/2016" ]

### ISSUE THREAD

**Issue by asmith26** [hadley/lubridate#426]
Hi there,

I'm using a script that works out when a subscription started, given the end date and the number of months the subscription lasts (e.g. for a 3-months subscription that ended on `"31/05/2016", I would use` `dmy("31/05/2016")  - months(3) + days(1)` and would expect a result like "01/03/2016").

I hoped lubridate would handle cases of subtracting from months that end on the 31st, however if the result date is a 30days (or 28days) month, lubridate just shows **NA**; e.g.:

```
> dmy("31/05/2016")  - months(3)
[1] NA
> dmy("31/05/2016")  - months(2)
[1] "2016-03-31"
> dmy("31/05/2016")  - months(4)
[1] "2016-01-31"
> dmy("31/05/2016")  - months(1)
[1] NA
```

I feel there must be a way of getting around this? Thanks for your help!

**Comment by vspinu** [comment]
See doc for `period` and `Period-class` for explanation on how arithmetic works with periods.

Use `‘%m-%` or `add_with_rollback` instead of `-`.

**Comment by vspinu** [comment]
> dmy("31/05/2016") - months(3) + days(1)

BTW, a more robust strategy might be `floor_date(dmy("31/05/2016"), "month") - months(2)`.
