### ISSUE TITLE
29th of Februar + years(1) returns NA

### ISSUE THREAD

**Issue by christophM** [hadley/lubridate#428]
Adding a year to a February 29th date returns NA. I think in some earlier version of lubridate the returned value was 1st of March of the next year, as mentioned here: http://stackoverflow.com/questions/8490799/how-to-account-for-leap-years

```r
> ymd("2000-2-29") + years(1)
[1] NA
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.5.6 RMySQL_0.10.9   DBI_0.4-1      

loaded via a namespace (and not attached):
[1] magrittr_1.5  tools_3.3.0   stringi_1.1.1 stringr_1.0.0
```

**Comment by vspinu** [comment]
Searching for `february NA` on lubridate page gives you [this](https://github.com/hadley/lubridate/search?q=february+NA&type=Issues&utf8=%E2%9C%93). This issue has been brought many times so far, most recent being #426 just a week ago which see for explanation. If you google the same query you will get this page on [%m+%](http://www.inside-r.org/node/163403) among top items which is exactly what you need.
