### ISSUE TITLE
`ceiling_date(date, 'month)` if `date` is the beginning of the month

### ISSUE THREAD

**Issue by ywhuofu** [hadley/lubridate#429]
Currently, `ceiling_date(ymd('1996-05-01'))` returns '1996-05-01'. For all the dates that other than the first date of the month, it returns the first day of the next month. This can be confusing, especially for the case below. I took it directly from the package vignettes

> Vectorization  The code in lubridate is vectorized and ready to be used in both interactive settings and within functions. As an example, I offer a function for advancing a date to the last day of the month  

>` last_day <- function(date) {   ceiling_date(date, "month") - days(1) } `

The function `last_day`, for example, will NOT advance a date to the last day of the month, if the date is the first day of the month.

**Comment by vspinu** [comment]
This is by design. Search for `ceiling_date` on github for motivation. You can use an extra argument `change_on_boundary` to change the behavior.
