### ISSUE TITLE
Removing the "UTC"? Question

### ISSUE THREAD

**Issue by skanskan** [hadley/lubridate#432]
Hello

If I run 
mdy("12/5/1945")
the date is shown as:
"1945-12-05 UTC"

How can I get only  "1945-12-05"  without the "UTC" part ?
I'm looking for a lubridate option. I don't mean modifying the string posteriori with substr.

I want to use it with a data.table to quickly convert many columns containing strings to date.

**Comment by vspinu** [comment]
There are two things going on there. First of all you are using old version of lubridate. There has been a change in [v1.5.6[(https://github.com/hadley/lubridate/releases/tag/v1.5.6) that makes `ymd` family of functions return Date instead of POSIXct. Thus the display is now exactly what you want:

```
> mdy("12/5/1945")
[1] "1945-12-05"
```

Secondly, you are confusing the display of the object with the object type. What you see is just a representation that `print` function prints out and it has little to do with the type of the object. Underlying object is numerc, not string as you seem to think.

**Comment by skanskan** [comment]
OK, thanks.
I've upgraded and now works well.

Anyway, if I have a big dataframe with many dates stored as characters "12/5/1945"...
How do you suggest to work with it?
Transform them with **as_date** or **fast_strptime** and store them in that new format or just keep them as  text and transform them just when I need to do compute something?

**Comment by vspinu** [comment]
> Transform that columns with as_date or fast_strptime and store them in that new format?, 

Yes. Furst use lubridate parsing functions -`ymd`, `ymd_hms`, `parse_date_time`, or lower level  ones - `parse_date_time2`, `fast_strptime`.  Then store your data with `saveRDS` for future processing. 

As date-time objects are essentially numbers (except for POSIXlt) it will likely take much less space than keeping them as strings.

**Comment by skanskan** [comment]
Or just   as_date("12/5/1945","%m/%d/%Y")  ?
It seems to be faster with my data.  
My intention is to use the data.table library, and store the data with its fwrite function, that creates a csv file that can be read very quickly, even compressed.

**Comment by vspinu** [comment]
>  as_date("12/5/1945","%m/%d/%Y") ?

I very much doubt it

```r
> tt <- rep.int("12/5/1945", 1e7)
> system.time(kk <- parse_date_time2(tt, "mdY"))
   user  system elapsed 
  0.504   0.020   0.523 
> system.time(kk <- as_date(tt,"%m/%d/%Y"))
   user  system elapsed 
  4.080   0.060   4.143 
```
> and store the data with its fwrite function, that creates a csv file that can be read very quickly, even compressed.

Whole round trip will still likely to be considerably slower than using uncompressed binary format, but sure, use whatever is more convenient for your needs.  CSV could be read by other programs and that's a big advantage.

**Comment by skanskan** [comment]
You are right, as_date is slower with your data, and in my test fast_strptime seems to be the fastest.

**Comment by vspinu** [comment]
`lt=FALSE` should give you the same speed as `parse_date_time2`. Conversion at the end is the only major difference besides the UI. See the code.

**Comment by Kennedybrilliance** [comment]
@skanskan https://stackdev.space/questions/transform-a-column-into-a-datetime-format-by-eliminating-specific-character-segments
