### ISSUE TITLE
lt = TRUE doesn't work

### ISSUE THREAD

**Issue by skanskan** [hadley/lubridate#433]
Hello.

I've being trying the examples and I think the lt option doesn't work.

> parse_date_time2("2010-03-14 02:05:06",  "YmdHMS", tz = "America/New_York", lt = TRUE)
> Error in parse_date_time2("2010-03-14 02:05:06", "YmdHMS", tz = "America/New_York",  : 
>   unused argument (lt = TRUE)

**Comment by vspinu** [comment]
It's there. Re-install and try again.
