### ISSUE TITLE
Support units in floor_date() etc

### ISSUE THREAD

**Issue by hadley** [hadley/lubridate#442]
i.e.

```R
floor_date(now(), "2 weeks")
```

**Comment by Yeedle** [comment]
was looking for similar functionality for rounding dates, e.g. `round_date(x, "5 minutes")`

**Comment by vspinu** [comment]
I have implemented this and added quite some tests, but would really appreciate if you guys could play with it a bit and run your own checks on corner cases. 

Multiple of all units excepts `weeks` are supported (updating on weeks is not supported by POSIXlt) .  Rounding on units that don't have a meaningful 0 (days and months) happens incrementally from 1:

```R
> floor_date(ymd("2016-08-02"), "2 days")
[1] "2016-08-01"
> floor_date(ymd("2016-08-03"), "2 days")
[1] "2016-08-03"
```` 
This is consistent with how currently `bimonthly`, `quarter` and `halfyear` behave.
