### ISSUE TITLE
Down play durations?

### ISSUE THREAD

**Issue by hadley** [hadley/lubridate#444]
Just noticed that base R now has a `c.difftime()` method that does the right thing

``` r
x1 <- as.difftime(24, units = "hours")
x2 <- as.difftime(86400, units = "secs")
c(x1, x2)
#> Time differences in secs
#> [1] 86400 86400
```

**Comment by vspinu** [comment]
Downplay in what sense? Deprecate? 

I think most of the folks are using difftime anyways so it's not a big loss. But difftime has its unfortunate problems when it comes to automatic conversions.

**Comment by vspinu** [comment]
I don't know what to do with this. It's too late to re-fit the whole package on difftime. If we suddenly start returning difftime instead of durations it will likely create huge backward compatibility problems.  

 If you have more concrete ideas, please reopen.
