### ISSUE TITLE
When passed a year, `parse_date_time()` returns the last day of the previous year.

### ISSUE THREAD

**Issue by toph-allen** [hadley/lubridate#448]
When using lubridate 1.5.6, `parse_date_time()` returns an incorrect value when evaluating a year by itself. For example:

```r
> parse_date_time("2016", orders = "y")
[1] "2015-12-31 UTC"
> parse_date_time("2016", orders = "y") %>% year()
[1] 2015
```

Reverting to 1.5.0 fixes this.

```r
> parse_date_time("2016", orders = "y")
[1] "2016-01-01 UTC"
> parse_date_time("2016", orders = "y") %>% year()
[1] 2016
```

This doesn't seem to happen with other orders, e.g. `"ymd"`.

**Comment by vspinu** [comment]
I think this was the consequence of #418.
