### ISSUE TITLE
Output in examples

### ISSUE THREAD

**Issue by hadley** [hadley/lubridate#456]
e.g. in `coercion.r`, why do we have the output pasted into the examples?

```R
#' dt_utc <- ymd_hms("2010-08-03 00:50:50")
#' dt_europe <- ymd_hms("2010-08-03 00:50:50", tz="Europe/London")
#' c(as_date(dt_utc), as.Date(dt_utc))
#' ## [1] "2010-08-03" "2010-08-03"
```

This seems like an easy way to end up with code and results out of sync.

**Comment by vspinu** [comment]
That's a custom for lubridate. I don't think it was me who started it, I think I just followed on the style. While it's a bit tedious to maintain it's surely convenient for the user.   Deleting those comments would be wasteful IMO,  especially now when the API is stable.

**Comment by hadley** [comment]
I think it's a bad idea because it's inconsistent with other packages, and there are definitely already differences between the output and the comment.  Good writing/coding involves being willing to delete stuff that no longer works.

**Comment by vspinu** [comment]
When [viewed online](http://finzi.psych.upenn.edu/library/lubridate/html/parse_date_time.html) or in a pdf printout this inline output is definitely useful. Many people are still printing doc pages (I see it all the time with my students). 

I personally wouldn't care as I can execute and edit code directly form the help page in ESS. In other editors you cannot do that and people have to  peruse the help page or have to run `examples(...)`.  

In any case, if you feel strongly about it then let's remove them. It would save me some time in the future. Manually pasting output is not the most pleasant activity.

**Comment by hadley** [comment]
I have some free time I'll have a go at removing it.  It's not very high priority, but I think it's worthwhile.
