### ISSUE TITLE
Feature request: timestamp

### ISSUE THREAD

**Issue by drknexus** [hadley/lubridate#457]
One date format `package:lubridate` doesn't seem to support directly is unix timestamps (seconds since 1970-01-01 00:00:00).  

A helper along the lines of:

```
#' @examples
#' as.timestamp("1970-01-02") == 86400
#' as.timestamp("1970-01-02 00:00:00") == 86400
#' as.timestamp(days(1))
setGeneric("as.timestamp",def = function(time) {
  stop("input must be a vector of character, POSIXct, or integer64")
})
setMethod("as.timestamp", signature = "integer64", function(time) {
  return(time)
})
setMethod("as.timestamp", signature = "numeric", function(time) {
  return(time)
})
setMethod("as.timestamp", signature = "Date", function(time) {
  return(as.numeric(difftime(time,as.Date("1970-01-01"),units="secs") %>% as.integer()))
})
setMethod("as.timestamp", signature = "POSIXct", function(time) {
  return(as.numeric(difftime(time,as.Date("1970-01-01"),units="secs") %>% as.integer()))
})
setMethod("as.timestamp", signature = "character", function(time) {
  return(as.numeric(difftime(as.POSIXct(time),as.Date("1970-01-01"),units="secs") %>% as.integer()))
})
setMethod("as.timestamp", signature("Period"), function(time) {
  as.numeric(difftime(ymd("2000-01-01")+time, ymd("2000-01-01"), units = "secs"))
})
```

Seems potentially useful.  ... obviously this isn't written in a way that takes advantage of the idioms in lubridate - the code above is merely illustrative.

Does that fall in the scope of things you'd like to see lubridate able to handle/do?

**Comment by vspinu** [comment]
You can get unix time with `as.integer(time)` for POSIX objects. Having new method just for the sake of Date object doesn't seem like a particularly useful feature.

**Comment by Karlheinzniebuhr** [comment]
You can do it very easily in [pandas ](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#from-timestamps-to-epoch)
```
stamps = pd.date_range("2012-10-08 18:15:05", periods=4, freq="D")
(stamps - pd.Timestamp("1970-01-01")) // pd.Timedelta("1s")
Int64Index([1349720105, 1349806505, 1349892905, 1349979305], dtype='int64')
```

**Comment by vspinu** [comment]
Date-time objects (aka POSIXct) in R are just classed unix timestamps. You can work with them directly as numbers.
