### ISSUE TITLE
Finance use case - tenor conversions to time spans

### ISSUE THREAD

**Issue by waynenilsen** [hadley/lubridate#459]
I thought I would add this as an issue, hoping that some functionality like this is already in lubridate. I have what we call tenors in finance, examples are `1w` `5d` `10y` etc. I think the `months` and `days` function serve this purpose however considering the ease-of-use nature of this library a convenience function would be great for converting these number-plus-span combinations into lubridate things. Let's call this function `tenor` for the sake of argument. The nature of this function would be such that

```
tenor('1d') = days(1)
tenor('1w') = weeks(1)
tenor('1m') = months(1)
tenor('1q') = quarters(1)
tenor('1y') = years(1)
```

Is there already something like this?

**Comment by vspinu** [comment]
Do I understand correctly that you want specialized parsers to get from `3d` into `days(3)`? 

`tenor` is obscure. I would better generalize the `period` constructor to be able to do `period("2d")` for this.

There is an internal unit parser since in lubridate:

```R
> lubridate:::parse_period_unit("1y")
$n
[1] 1

$unit
[1] "y"
```
That's the closest it gets at the moment.

**Comment by waynenilsen** [comment]
You understand the concept

The name I leave to you, period seems like a reasonable name for it. The `parse_period_unit` function would be helpful but it is not exposed.

Implementation could be along the lines below? I can take a stab if you want although I have never really gotten into R package dev before not sure about testing.

```

function_mapping = list(
	"Y" => years,
	"M" => months,
	...
)

period = function(spec) {
	parsed = parse_period_unit(spec)
	function_mapping[[parsed$unit]](parsed$n)
}
```

**Comment by vspinu** [comment]
> Were you thinking of adding another case here?

Yes. 

But let's think of a proper and consistent API first. I would very much prefer to have a more generic string parser. Something like `period("1d 2min") should also work. Pretty much like with current `period(days=1,months=2)` but within string.

Also need to check what ISO standard has to say about it. Related #362

**Comment by waynenilsen** [comment]
I certainly agree that parsing the ISO standards is an excellent goal to reach for.

My question is, how about both? That is, have the ability to parse simple `1y` as well as the full ISO specification. Perhaps the `period` function should parse according to ISO and this parsing could be in a separate function. 

Of course, if you would rather this functionality be external to lubridate, just let me know and I will close this issue and related PR.

**Comment by vspinu** [comment]
>  how about both?

Yes. This is the intention. I don't think it should be external to lubridate.  

I will give a stab at C parser for this and #362 when I have a bit of time. It will not happen by next release for sure (already next week).

**Comment by vspinu** [comment]
@waynenilsen what is the tenor abreviations for sub day units? 1H,1M,1S? If so that's compatible with strptime and would be very nice indeed.

**Comment by waynenilsen** [comment]
Unfortunately, in the case of tenors M is used for month, the tenors are always assumed to be a day or greater and generally interpreted in a case-insensitive way. H and S are fair game. A popular example is LIBOR 3M the three month London interbank offered rate. There is also LIBOR 6M and EURIBOR 6M for example.

**Comment by vspinu** [comment]
I have decided to fix this now. I need it to fix some misused of character comparison in a bunch of revdeps.

As a by product you can now directly compare to strings:

```R
> duration("day") < "day 1sec"
[1] TRUE
```

Arbitrary abreviation of units and repeated units is supported.

```R
> period("1sec 1second 1s 1 s")
[1] "4S"
````
