### ISSUE TITLE
Error after Update to R 3.3.1

### ISSUE THREAD

**Issue by shellmeier** [hadley/lubridate#461]
Hi all,

I am not sure if this is the right place to ask this, but I am encountering a problem using lubridate after updating R to version 3.3.1. 

The error that I am getting out of a sudden is the following:

> Error in .setupMethodsTables(fdef, initialize = TRUE) : 
  no slot of name "group" for this object of class "derivedDefaultMethod"``

Before the update everything was running fine. I need lubridate to calculate time intervals from two dates. The command looks like this:

`df$variable <- as.interval(ymd(df$start_date), ymd(df$end_date))`

I am using lubridate (V1.5.6).

If you have any suggestions how I can solve this issue I would be glad to hear your comments. 

Best regards,

Sebastian

Some more info:

> R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
 [1] data.table_1.9.6   reshape2_1.4.1     DataCombine_0.2.21 zoo_1.7-13         foreign_0.8-66     dplyr_0.5.0        plyr_1.8.4        
 [8] countrycode_0.18   pastecs_1.3-18     boot_1.3-18        lubridate_1.5.6   
loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6     lattice_0.20-33 assertthat_0.1  chron_2.3-47    grid_3.3.1      R6_2.1.3        DBI_0.5         magrittr_1.5    stringi_1.1.1  
[10] lazyeval_0.2.0  tools_3.3.1     stringr_1.1.0   tibble_1.1 

>

**Comment by vspinu** [comment]
Have you re-installed lubridate after R's upgrade? Try to re-install, if the problem persists install directly from source `devtools::install_github("hadley/lubridate")`.

**Comment by shellmeier** [comment]
Thanks for the reply. I re-installed lubridate (R and R studio as well) but still no change. 
When I install lubridate directly from source I get the following output. I am inclined to think that this is a problem that has to do with my package library. However, lubridate is the only package that is not working after the update. So if you have any idea why this is and why I get the warning during the download from source, please let me know. Thanks a lot in advance.

> Downloading GitHub repo hadley/lubridate@master
from URL https://api.github.com/repos/hadley/lubridate/zipball/master
Installing lubridate
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/_x/30jjn8dj2dq8qk3qrl7ztkb80000gn/T/RtmpGHdR75/devtools5e871621d2b/hadley-lubridate-1c5a655'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 
installing *source* package ‘lubridate’ ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c datetime.c -o datetime.o
datetime.c:164:6: warning: unused variable 'S' [-Wunused-variable]
        int S = 0;
            ^
1 warning generated.
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c tparse.c -o tparse.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c utils.c -o utils.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o lubridate.so datetime.o tparse.o utils.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/lubridate/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (lubridate)

>

**Comment by vspinu** [comment]
Oh. That's an inocuous warning from datetime.c. I will fix that.

To make sure,  your command should probably be

```R
interval(ymd("2016-01-01"), ymd("2018-04-05"))
```
right?

The version with `as.interval` as you have originally posted doesn't make sense. `as.interval` accepts one argument.

**Comment by shellmeier** [comment]
Thank you! And of course, you're right. The command should be as you said. And...it works. Having a closer look at the manual it is clear that `interval` is preferable to `as.interval`. I am wondering why `as.interval` worked with two `date` arguments before the update, though. Anyways, thanks again for your help.

**Comment by vspinu** [comment]
There have been some refactoring of dispatch on ESS side. I will check that out, but I am not entirely sure if we should support POSIX argument to `as.interval` in the first place.
