### ISSUE TITLE
Bug in dmy_h() 

### ISSUE THREAD

**Issue by aphalo** [hadley/lubridate#466]
dmy_h() has the same code as dmy_hm() and fails to decode valid input.

    dmy_h("05-07-2011 13")

returns
`[1] "2020-07-05 11:01:00 UTC"`

looks to me like `orders = "dmyR"` should be changed to `orders = "dmyr"` in the definition of this function.

**Comment by vspinu** [comment]
Thanks. Your diagnostic is correct.
