### ISSUE TITLE
Possibly a day light saving issue

### ISSUE THREAD

**Issue by aben-uchicago** [hadley/lubridate#468]
Came across this edge case issue:

ymd_hms('2016-03-13 1:59:00' , tz = 'America/Chicago') + seconds(60)

returns "2016-03-13 01:00:00 CST" instead of "2016-03-13 03:00:00 CDT"

ymd_hms('2016-03-13 1:59:00' , tz = 'America/Chicago') +  minutes(1) returns NA

**Comment by cderv** [comment]
With last lubridate dev version (hadley/lubridate@ac50217), 

``` r
ymd_hms('2016-03-13 1:59:00' , tz = 'America/Chicago') + seconds(60)
#> [1] NA
ymd_hms('2016-03-13 1:59:00' , tz = 'America/Chicago') + minutes(1)
#> [1] NA
ymd_hms('2016-03-13 1:59:00' , tz = 'America/Chicago') + dseconds(60)
#> [1] "2016-03-13 03:00:00 CDT"
ymd_hms('2016-03-13 1:59:00' , tz = 'America/Chicago') + dminutes(1)
#> [1] "2016-03-13 03:00:00 CDT"
```
It seems correct as both give the same results and `NA` is returned for `minutes` and `seconds` as it does not exist.

No more bug I think. Not sure which commit solved this issue.

**Comment by vspinu** [comment]
This is likely system and maybe R version dependent. I can still reproduce it on ubuntu linux with R3.2.4.

**Comment by vspinu** [comment]
@cderv has a good point there. Use `dseconds` and `dminutes` if you don't want NAs. The semantics of sub-day period arithmetics is somewhat non-intuitive around DST changes. See also #498.
