### ISSUE TITLE
ymd_hms returns wildly incorrect values when receiving partial dates

### ISSUE THREAD

**Issue by gowerc** [hadley/lubridate#471]
Lubridate's ymd_hms appears to attempt to do some sort of partial date completion however in some cases it returns wildly incorrect numbers. I guess I was expecting this to either impute to "00" or kick up an error message. 

    > ymd_hms("2007-06-04T15:22:00")
    [1] "2007-06-04 15:22:00 UTC"

    > ymd_hms("2007-06-04T15:22")
    [1] "2020-07-06 04:15:22 UTC"

**Comment by vspinu** [comment]
Use truncated argument:

```R

> ymd_hms(c("2007-06-04T15", "2007-06-04T15:22",  "2007-06-04T15:22:00"), truncated = 2)
[1] "2007-06-04 15:00:00 UTC" "2007-06-04 15:22:00 UTC" "2007-06-04 15:22:00 UTC"
```

One needs to make small concessions in order to be able to automatically recognize a plethora of formats. This is one of them.
