### ISSUE TITLE
inconsistent date class output

### ISSUE THREAD

**Issue by 07engineer** [hadley/lubridate#476]
Documentation indicates lubridate functions output POSIXct objects. Now, dates without time produce Date objects. 

`str(mdy("9/22/2016"))`
 Date[1:1], format: "2016-09-22"

`str(mdy_hms("9/22/2016 10:00:00"))`
 POSIXct[1:1], format: "2016-09-22 10:00:00"

I'm using lubridate_1.5.6, 
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by vspinu** [comment]
See #391. Also update your lubridate, it's all there in the docs.
