### ISSUE TITLE
wrong return type in `ceiling_date` when unit = "week"

### ISSUE THREAD

**Issue by shrektan** [hadley/lubridate#479]
Hi, @vspinu, I tried the CRAN version of `lubridate` and found a bug related to `ceiling_date` when the `unit = "week"`. It should return a date object instead of a datetime. 

Here's the reproducible example:

```r
library(lubridate)

# ceiling date returns a time
ceiling_date(ymd("20160927"), "week")
## [1] "2016-10-02 08:00:00 CST"

# while the floor_date returns a date
floor_date(ymd("20160927"), "week")
## [1] "2016-09-25"
```

**Comment by shrektan** [comment]
I've filed a PR.

**Comment by vspinu** [comment]
>  It should return a date object instead of a datetime. 

Why do you think so?

 If it returns date for week, shouldn't it return date for "day",  "month" and "year" as well?

**Comment by shrektan** [comment]
It's true that day month and year returns a date. Isn't it?

**Comment by shrektan** [comment]
@vspinu Here's is what's returned in `lubridate version 1.6.0`. As you can see, only `unit = "week"` behaves differently.

```r
ceiling_date(ymd("20160927"), "year")
## [1] "2017-01-01"
ceiling_date(ymd("20160927"), "month")
## [1] "2016-10-01"
ceiling_date(ymd("20160927"), "week")
## [1] "2016-10-02 08:00:00 CST"
ceiling_date(ymd("20160927"), "day")
## [1] "2016-09-28"
```

**Comment by vspinu** [comment]
Yes. You are right. I got confused for a second due to recent re-designing of rounding API.

**Comment by shrektan** [comment]
It's a very powerful and useful package. Certainly it takes lots of effort to improve. 🍺

**Comment by Henrik-P** [comment]
Seems like this issue is alive again in `lubridate_1.6.0`:

```
ceiling_date(ymd("20160927"), "year")
# [1] "2017-01-01"

ceiling_date(ymd("20160927"), "month")
# [1] "2016-10-01"

ceiling_date(ymd("20160927"), "week")
# [1] "2016-10-02 02:00:00 CEST"

ceiling_date(ymd("20160927"), "day")
# [1] "2016-09-28"

```

**Comment by cderv** [comment]
It is ok in current development version of lubridate 1.6.0.9009. 

``` r
library(lubridate)
ceiling_date(ymd("20160927"), "year")
#> [1] "2017-01-01"
ceiling_date(ymd("20160927"), "month")
#> [1] "2016-10-01"
ceiling_date(ymd("20160927"), "week")
#> [1] "2016-10-02"
ceiling_date(ymd("20160927"), "day")
#> [1] "2016-09-28"
```
