### ISSUE TITLE
Request: ``start_of_*`` functions

### ISSUE THREAD

**Issue by kendonB** [hadley/lubridate#481]
These would be ``start_of_month(date)``, ``start_of_year(date)``,  ``start_of_week(date)``.

I and many others always use the start of a period in ``Date`` type to index months, years, weeks, etc.

These would be good convenience functions and seem to fit in the philosophy of lubridate.

**Comment by kendonB** [comment]
Something like:

```
start_of_month <- function(date){
  date - mday(date) + 1
}

start_of_week <- function(date){
  date - mday(date) + 1
}
start_of_month <- function(date){
  date - mday(date) + 1
}
```
These are, of course, easy. But having these functions would be self-documenting and less error prone.

**Comment by vspinu** [comment]
Would `floor_date` do what you need?

**Comment by kendonB** [comment]
Yes.
