### ISSUE TITLE
Can not download lubridate

### ISSUE THREAD

**Issue by marianaolivares** [hadley/lubridate#482]
I just recently started using RStudio, and for some work at the University is is required to download lubridate, which was impossible to do. The output at the Console said:

> install.packages("lubridate")
Installing package into ‘C:/Users/Mariana/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘lubridate’ is not available (for R version 3.3.1)

I don't know what to do, and the package seems very useful. I'm very sorry it it's a easy fix. I really need help!
Thanks.

**Comment by vspinu** [comment]
Looks like CRAN problem. Change your CRAN mirror or install directly from github with `devtools::install_github("hadley/lubridate")`.
