### ISSUE TITLE
make_datetime creates time in UTC instead of supplied timezone

### ISSUE THREAD

**Issue by t-kalinowski** [hadley/lubridate#491]
This is different from `ISOdateTime`
```
lubridate::make_datetime(2016, 10, 15, 0,0,0 , tz = "America/New_York")
[1] "2016-10-14 20:00:00 EDT"
ISOdatetime(2016, 10, 15, 0,0,0 , tz = "America/New_York")
[1] "2016-10-15 EDT"
```

from the docs: 
> make_datetime is a very fast drop-in replacement for base::ISOdate and base::ISOdatetime.

**Comment by vspinu** [comment]
Indeed. `force_tz` must be used instead. It will slow down the date creation considerably :(.

**Comment by vspinu** [comment]
Fixed, with new update functionality, this is very fast even for non-UTC tzones.
