### ISSUE TITLE
Length-dependent ymd() parsing error

### ISSUE THREAD

**Issue by coolbutuseless** [hadley/lubridate#494]
I found a weird error in parsing out dates that seems dependent on the length of the vector being parsed and how many valid results are in this vector!

This seems to happen with `ymd_hm` parsing as well. I haven't tried the others.

What's going on?  Am I just mis-understanding how lubridate works on vectors of values?

```r
library(lubridate) # v1.6.0   R3.3.2.  OSX.


# ----------------------------------------------------------------------------
# Large number of invalid ymd() dates, followed by a valid one
# Expect 1 valid result. Get 0 valid results :(
# ----------------------------------------------------------------------------
dates <- c(rep("2015-01", 1000), "2015-09-14")
sum(!is.na(ymd(dates, quiet=TRUE)))  # Expect 1, get 0


# ----------------------------------------------------------------------------
# 131 Invalid ymd() dates, followed by a valid one.
# Expect 1 valid result. Get 0 valid result :(
# ----------------------------------------------------------------------------
dates <- c(rep("2015-01", 131), "2015-09-14")
sum(!is.na(ymd(dates, quiet=TRUE)))  # Expect 1, get 0


# ----------------------------------------------------------------------------
# 130 Invalid ymd() dates, followed by a valid one
# Expect 1 valid result. Get 1 valid result!!!
# ----------------------------------------------------------------------------
dates <- c(rep("2015-01", 130), "2015-09-14")
sum(!is.na(ymd(dates, quiet=TRUE)))  # Expect 1 valid result. Get 1 valid result!  :O


# ----------------------------------------------------------------------------
# 131 invalid ymd() dates, followed by 5 valid ones
# Expect 5 valid results, get 0.
# ----------------------------------------------------------------------------
dates <- c(rep("2015-01", 131), rep("2015-09-14", 5))
sum(!is.na(ymd(dates, quiet=TRUE)))  # Expect 5 valid results. Get 0 valid results  :(


# ----------------------------------------------------------------------------
# 131 invalid ymd() dates, followed by 6 valid ones
# Expect 6 valid results, get 6.
# ----------------------------------------------------------------------------
dates <- c(rep("2015-01", 131), rep("2015-09-14", 6))
sum(!is.na(ymd(dates, quiet=TRUE)))  # Expect 6 valid results. Get 6 valid results  :O
```

**Comment by cderv** [comment]
Yes there is an issue with dev version too. 

Looking shorthly where it could be I found that the problem occurs when `length(dates) > 100` and it is linked to the function `lubridate:::.get_train_set` which has a condition `len<100`
```r
.get_train_set <- function (x) 
{
  x <- x[!.enclosed.na(x)]
  len <- length(x)
  if (len < 100) 
    x
  else if (len < 3571) 
    x[.primes[.primes <= length(x)]]
  else x[.primes * (length(x)%/%3571)]
}
```
I understand this train set is used to guess formats and with an `x>=100` only a part of x is considered as train set not all (prime number index it seems). It is why it could not guess the right format for `dates`.

I will let @vspinu look into it before going further because he knows better the design.

**Comment by vspinu** [comment]
> I understand this train set is used to guess formats and with an x>=100 only a part of x is considered as train set not all (prime number index it seems). It is why it could not guess the right format for dates.

Yes. That's exactly right. See #307 for a discussion. There is really no defenitive solution for this.

**Comment by vspinu** [comment]
`parse_date_time` has an argument `exact` which, when set to TRUE, will avoid training. But you will need to supply all your formats in the `strptime` form then.
