### ISSUE TITLE
Daylight Savings Time inconsistent with POSIXct (but lubridate might be right)

### ISSUE THREAD

**Issue by mpettis** [hadley/lubridate#497]
I am seeing an inconsistency of lubridate daylight savings time casting (with `parse_date_time()`) with what `strptime()` and `as.POSIXct()` give me.  However, I am thinking that perhaps `parse_date_time()` is correct?  I want to check here first that lubridate is correct, otherwise, perhaps a bug needs to be filed with core R?

Below is my output.  My main concern is that:

`"11/2/2014 1:15:00 AM"` is DST for as.POSIXct() and strptime, but is standard time for lubridate.

but

 `"11/2/2014 1:55:00 AM"` parses to standard time for all three functions.  This makes lubridate consistent, but the other two not, so I think lubridate is correct here?

Possibly related to: https://github.com/hadley/lubridate/issues/468

Code here:

    > library(lubridate)

    Attaching package: ‘lubridate’

    The following object is masked from ‘package:base’:

        date

    Warning message:
    package ‘lubridate’ was built under R version 3.3.2 
    > 
    >   ## Datetimes span datetimes on which clocks roll back
    > dt_str1 <- c("11/2/2014 12:15:00 AM", "11/2/2014 1:15:00 AM", "11/2/2014 1:55:00 AM", "11/2/2014 2:15:00 AM")
    >   
    > parse_date_time(dt_str1, orders='%m/%d/%Y %I:%M:%S %p', tz="America/Los_Angeles")
    [1] "2014-11-02 00:15:00 PDT" "2014-11-02 01:15:00 PST" "2014-11-02 01:55:00 PST" "2014-11-02 02:15:00 PST"
    > as.POSIXct(dt_str1, format='%m/%d/%Y %I:%M:%S %p', tz="America/Los_Angeles")
    [1] "2014-11-02 00:15:00 PDT" "2014-11-02 01:15:00 PDT" "2014-11-02 01:55:00 PST" "2014-11-02 02:15:00 PST"
    > strptime(dt_str1, format='%m/%d/%Y %I:%M:%S %p', tz="America/Los_Angeles")
    [1] "2014-11-02 00:15:00 PDT" "2014-11-02 01:15:00 PDT" "2014-11-02 01:55:00 PST" "2014-11-02 02:15:00 PST"
    > 
    > R.version
                   _                           
    platform       x86_64-w64-mingw32          
    arch           x86_64                      
    os             mingw32                     
    system         x86_64, mingw32             
    status                                     
    major          3                           
    minor          3.1                         
    year           2016                        
    month          06                          
    day            21                          
    svn rev        70800                       
    language       R                           
    version.string R version 3.3.1 (2016-06-21)
    nickname       Bug in Your Hair            
    > packageVersion("lubridate")
    [1] ‘1.6.0’

**Comment by vspinu** [comment]
> "11/2/2014 1:55:00 AM" parses to standard time for all three functions.

Not really. It parses to DST on my machine. So it's system dependent and not R's problem per se. The string `11/2/2014 1:15:00 AM` represents a time that occurred twice (what a mess). So the parsing behavior is undefined. Different systems have different conventions.  

BTW, `mdy_hms(dt_str1, tz = "America/Los_Angeles")` recognizes these formats just fine.

**Comment by vspinu** [comment]
Little I can do here. So, closing. If you have some further ideas feel free to re-open.
