### ISSUE TITLE
month function error

### ISSUE THREAD

**Issue by chilianlin87** [hadley/lubridate#501]
while my date is "2016-01-31 19:00:00", I use month function to get month part, it gave me Feb,
for date "2016-02-29 19:00:00" it gave me Mar, for date "2016-03-31 20:00:00", it gave me Apr. So weird.

**Comment by vspinu** [comment]
Can you provide some more details? A code example and specifics of your system (OS, timezone, R version and lubridate version).

Also make sure you are calling `month` from lubridate. There are `month` functions in other packages as well:

```r
> month
function(x, label = FALSE, abbr = TRUE)
  UseMethod("month")
<environment: namespace:lubridate>
```

**Comment by chilianlin87** [comment]
I solved this problem. I used these two steps.
pickdate$date <- format(pickdate$Confirmation_date, format = "%m/%d/%Y", tz="UTC")
pickdate$Confirmation_date <- as.Date(pickdate$date, format = "%m/%d/%Y")

For my daily work, I only care about date, I don't care about time and time zone at all. I used to use SAS, which has no problem at all. But R always save date with time zone, which caused me some trouble.

**Comment by chilianlin87** [comment]
Thank you very much anyway.

**Comment by vspinu** [comment]
Ok. Closing as non-reproducible.
