### ISSUE TITLE
ceiling_date returns an error when it is given a vector as input and it includes NAs

### ISSUE THREAD

**Issue by pchtsp** [hadley/lubridate#504]
Hello,

I've recently come into the following issue: `ceiling_date` is not working correctly when there is at least one NA being rounded.
The `floor_date` function works correctly. I probably updated the package recently because I'm sure this was not happening before.

For example:
    
    lubridate::floor_date(as.POSIXct(c(NA, NA)), "day")
    lubridate::ceiling_date(as.POSIXct(NA), "day")
    lubridate::ceiling_date(as.POSIXct(c(NA, NA)), "day")

The first one gets `c(NA, NA)`. OK.
The second one gets `NA`. OK.
The third one gets the following message:
    
    Error in `[<-.POSIXlt`(`*tmp*`, not_same, value = c(NA_real_, NA_real_ : 
      NAs are not allowed in subscripted assignments
      

Other information:
    
    R version 3.3.1 (2016-06-21)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)

    locale:
    [1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252
    [4] LC_NUMERIC=C                   LC_TIME=Spanish_Spain.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] lubridate_1.6.0

    loaded via a namespace (and not attached):
    [1] magrittr_1.5    rsconnect_0.4.3 tools_3.3.1     stringi_1.1.2   stringr_1.1.0

**Comment by cderv** [comment]
Hello, 

With last development version 1.6.0.9009, it is working well
``` r
lubridate::floor_date(as.POSIXct(c(NA, NA)), "day")
#> [1] NA NA
lubridate::ceiling_date(as.POSIXct(NA), "day")
#> [1] NA
lubridate::ceiling_date(as.POSIXct(c(NA, NA)), "day")
#> [1] NA NA
```

<details><summary>Session info</summary>

``` r
devtools::session_info("lubridate")
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.3.2 (2016-10-31)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  French_France.1252          
#>  tz       Europe/Paris                
#>  date     2017-01-07
#> Packages -----------------------------------------------------------------
#>  package   * version    date       source                           
#>  lubridate   1.6.0.9009 2017-01-07 Github (hadley/lubridate@ac50217)
#>  magrittr    1.5        2014-11-22 CRAN (R 3.3.2)                   
#>  stringi     1.1.2      2016-10-01 CRAN (R 3.3.2)                   
#>  stringr     1.1.0      2016-08-19 CRAN (R 3.3.2)
```

</details>

**Comment by pchtsp** [comment]
Thanks!
Any idea when it is going to be available in CRAN?

**Comment by cderv** [comment]
I don't know. @vspinu may be able to answer to this.

However, in the meantime, you can use dev version by installing from github with `devtools::install("hadley/lubridate")` or `devtools::install_github("hadley/lubridate@ac50217")` to install version I use in my answer above.

**Comment by vspinu** [comment]
CRAN is a bit overdue. I will try to push it there by the end of the month. There are a couple of critical issues that need to be fixed first.
