### ISSUE TITLE
Conversion of time using hms()

### ISSUE THREAD

**Issue by kkalafut** [hadley/lubridate#505]
When importing a character string of times (08:08:48.63, for example), and then attempting to sparse into H M S using hms(). 

Using the following code: 
hms(data$time) 
returns 
11H 18M 48.63S

The data going in is 08:08:48.63, the time coming out is 11H 18M 48.63S. 
Am I missing something about the functionality of hms? 
I should mention that this error occurs while using the 'mutate' function, as follows: 

data <- read_csv("Jan_9_2017.csv", col_names=col_names, col_types="ccccccccc") %>%
  filter(detection=="D", antenna %in% c("A1", "A2", "A3", "A4")) %>%
  mutate(penguin = factor(penguin, levels=penguin_ids, labels=penguin_names),
         #time = hms(time),
         date = mdy(date),
         duration = as.duration(hms(duration))) %>%
  filter(date >= "2017-1-3") %>%
  arrange(penguin, date, time)

**Comment by cderv** [comment]
Did you check for timezone issue in your session ? 
'hms("08:08:48.63")' is working fine for me. Is your results return in another timezone for printing for example? 

For your case using 'mutate', try to come with a reproductible example please. Easier to help you.

**Comment by vspinu** [comment]
Works fine for me as well. What version of lubridate is this? Make sure you are up to date.
