### ISSUE TITLE
Help for confusing `strftime()`?

### ISSUE THREAD

**Issue by kenahoo** [hadley/lubridate#513]
The built-in `base::strftime` function has some dangerous pitfalls around timezones:

```
> d <- strptime('2005-03-26 12:00:01', "%F %T", tz='America/New_York')
> d
[1] "2005-03-26 12:00:01 EST"
> tz(d)
[1] "America/New_York"

# Bad: wrong offset shown - this is actually the wrong instant
> strftime(d, "%F %T%z")
[1] "2005-03-26 12:00:01+0000"

# Bad: timezone is lost - this is the right instant but in the wrong timezone
> strftime(as.POSIXct(d), "%F %T%z")
[1] "2005-03-26 17:00:01+0000"
> strftime(as.POSIXct(d, tz=tz(d)), "%F %T%z")
[1] "2005-03-26 17:00:01+0000"

# Good
> strftime(as.POSIXct(d), "%F %T%z", tz=tz(d))
[1] "2005-03-26 12:00:01-0500"
```

Since `lubridate`'s niche is (at least in part) to help people avoid these pitfalls with alternative functions like `as_posixct()`, have you thought about adding a helper function people could use instead of `strftime()` that would have safer default semantics?

**Comment by vspinu** [comment]
Time zones are very tricky. No way this could be implemented in lubridate itself. Closing this as a differal to #396. Only after we port to cctz we can talk about custom strftime.

**Comment by kenahoo** [comment]
I'm not sure it's particularly tricky - it really just needs to _not lose_ the timezone, rather than actually doing anything with it.

Certainly might be better to have `cctz` in place before this, but in the meantime we'll probably have to write a workaround function for ourselves like `format_datetime <- function(x, format) { strftime(as.POSIXct(x), format, tz=lubridate::tz(x)) }` just to avoid buggy output, and it seems like such a thing might have a better home in a public package than in our private codebase.
