### ISSUE TITLE
Format guessing code in parse_date_time broke my code !

### ISSUE THREAD

**Issue by finlay** [hadley/lubridate#516]
After reading the code, I realised what was happening, but it killed an afternoon.

I found that there is an issue here #308, and am now using the "exact" flag.

My only suggestion is that there should be something more in the documentation. Currently there is only one reference to the "training", without any explanation what it does:
```
exact: logical. If TRUE, orders parameter is interpreted as an exact strptime format
and no trainign or guessing are performed.
```

Perhaps a short description of what the training actually does, and why you might want to not use it. And perhaps a flag synonym like "training=FALSE" to make it easier to understand the code where it is used.

**Comment by vspinu** [comment]
Yes, this is an thorny issue and better documentation is the only way to "fix" that.

**Comment by vspinu** [comment]
Fixing this by providing two new parameters `train=TRUE` and `drop=FALSE`. You have full control now on parsing.

**Comment by finlay** [comment]
Thanks
