### ISSUE TITLE
duration() ignores decimal elements when parsing

### ISSUE THREAD

**Issue by jspncr** [hadley/lubridate#519]
```{r}
> duration("1.5 hours")  
[1] "3600s (~1 hours)"
```

**Comment by cderv** [comment]
I think it is a duplicate and fixed by #465. 
Have you tried last dev version?

**Comment by jspncr** [comment]
Yes, you are correct. Sorry, I should have checked the dev version first.

**Comment by cderv** [comment]
No problem. You will next time :) 
Can you close the issue as it is ok and already corrected ?

**Comment by jspncr** [comment]
Wait, i'm an idiot. I tested `duration(1.5, "hours")`, not `duration("1.5 hours")`

The issue remains.

```{r}
> duration("1.5 hours")
[1] "3600s (~1 hours)"
> duration(1.5, "hours")
[1] "5400s (~1.5 hours)"
```

(lubridate_1.6.0.9009)

**Comment by cderv** [comment]
OK I see. `duration` takes two arguments `num` et `units` default to `"seconds"`. `num` can take numeric or character, but it seems that when character, it do not handle decimal duration.

``` r
library(lubridate)
#> 
#> Attachement du package : 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
duration("1.5 hours")
#> [1] "3600s (~1 hours)"
duration("1 hour 30 min")
#> [1] "5400s (~1.5 hours)"
duration(1.5,  "hours")
#> [1] "5400s (~1.5 hours)"
```

behind the scene when `num` is character, it calls `lubridate:::parse_period` that do not handle decimal;
``` r
lubridate:::parse_period("1.5 hours")
#> [1] "1H 0M 0S"
```
that is converted to duration and returns `"3600s (~1 hours)"`.

So, 

 + either `parse_period` is supposed to handle decimal in the character parsing and it should be corrected, tested and documented 
 + or it is not intended and it should at least be documented. 

Not my decision, we should wait for @vspinu advice.

**Comment by vspinu** [comment]
It's a limitation of the unit parsing mechanism. Fractional units are not recognized yet. It will be fixed on the before the next release.
