### ISSUE TITLE
convert to ymd fails

### ISSUE THREAD

**Issue by Monduiz** [hadley/lubridate#520]
Given this date format in this example:

    library(lubridate)
    time <- c("2017/07/18 13:33:33+00", "2017/07/19 13:33:33+00", "2017/07/20 13:33:33+00", "2015/07/21 13:33:33+00")
    name <- c("test1", "test2", "test3", "test4")

    data <- data.frame(time, name)

Why this doesn't work:

    data$time <- ymd(data$time)

But this does:
    
    data$time <- as.Date(data$time)

**Comment by vspinu** [comment]
Because lubridate realizes that you are probably making a mistake and doesn't parse your date-time as date. 

Do 

```R
> ymd_hms(data$time)
[1] "2017-07-18 13:33:33 UTC" "2017-07-19 13:33:33 UTC" "2017-07-20 13:33:33 UTC" "2015-07-21 13:33:33 UTC"
> as_date(ymd_hms(data$time))
[1] "2017-07-18" "2017-07-19" "2017-07-20" "2015-07-21"
>
```

**Comment by Monduiz** [comment]
Somehow I believed that the logic would be to extract the ymd and make an object in that format since the reason I would use ymd() would be to get that. So it would be ymd_hms first, and then ymd(), so a two steps process instead of one?

**Comment by vspinu** [comment]
ymd and ymd_hms are parsers. Input is always string. You get posixct date-time first and then extract the date component if you need so. It's a two step process. 

In principle it would be possible to recur to trivial heuristic and parse first 3 numbers as Date but it's not something that could be done right now. I will probably start extracting parsing code into a separate package soon and will keep this option in mind.

**Comment by Monduiz** [comment]
Thank you for the explanation! It makes a lot of sense now.
