### ISSUE TITLE
Adding hour duration some times fails to coerce date to POSIXct

### ISSUE THREAD

**Issue by hadley** [hadley/lubridate#522]
``` r
library(lubridate, warn.conflicts = FALSE)

x <- rep(as.Date("2010-01-01"), 2)
x + dhours(0:1)
#> [1] "2010-01-01" "2010-01-01"
x + dhours(1:0)
#> [1] "2010-01-01 01:00:00 UTC" "2010-01-01 00:00:00 UTC"
```

From https://github.com/hadley/dplyr/issues/2068

**Comment by vspinu** [comment]
I don't see this in master with R3.3.3 on linux. So either it was automagically fixed, or it's OS/R dependent. Could you please check this again?

**Comment by hadley** [comment]
I get the correct result after installing from GitHub
