### ISSUE TITLE
Working just months and dates for a plot

### ISSUE THREAD

**Issue by boshek** [hadley/lubridate#523]
I find myself using lubridate often and really appreciate the ability to extract month and day from a date object. I do often want to compare  year to year variation  on a plot. I have been using this function:

```
md <- function(Date) {
  return(ymd(paste0("1904","-",month(Date),"-", day(Date))))
}
```
 So this data:
```
library(tidyverse)
library(lubridate)

Date=seq.Date(from = ymd("2000-01-01"), to = ymd("2004-12-31"), by = "day")
Value=rnorm(length(Date))
df1 <- tibble(Date,Value)
```

Plots like this with a common date axis:
![image](https://cloud.githubusercontent.com/assets/18472598/23382684/10477578-fcf8-11e6-9c7c-cd9124b753d4.png)
```
df1 %>%
  mutate(Year = year(Date), Date2 = md(Date)) %>%
  ggplot(aes(x = Date2, y = Value)) +
  geom_point() +
  facet_wrap(~Year)
```

Rather than this:
![image](https://cloud.githubusercontent.com/assets/18472598/23382660/f385d2a4-fcf7-11e6-9291-97afca7a3de4.png)
```
df1 %>%
  mutate(Year = year(Date), Date2 = md(Date)) %>%
  ggplot(aes(x = Date, y = Value)) +
  geom_point() +
  facet_wrap(~Year)
```
I  have looked around but I am just wondering if there is a more "lubridate"-y way of doing this. It is a definite hack to simply put "1904" as a place holder date. This really becomes relevant with a plot when year is a factor level of interest.

**Comment by vspinu** [comment]
The closest function to your `md` is `year<-`:

```R
year(date) <- 2000
## or
 `year<-`(date, 2000) 
```

Alternatively you can try the difftime from base R:

```R
difftime(date, make_date(year(date)), unit = "days")
```
`difftime` doesn't allow monthly unitis, but you can use `time_length` from lubridate to get those:

```R
interval(make_date(year(date)), date) %>% time_length("month")
## or
interval(floor_date(date, "year"), date) %>% time_length("month")
```

**Comment by boshek** [comment]
Ok thanks. For certain your method is more efficient than mine. But if a sole month-day date type not exist this seems like a gap in functionality no? Maybe this is a ggplot2 issue but wouldn't it be useful to have the ability to use just day and month as a scale type to compare years?

**Comment by vspinu** [comment]
Partial date-times are out of scope. R supports only one partial date time - Date. We have to live with that.
