### ISSUE TITLE
`as_datetime()` doesn’t really respect `tz` for character objects

### ISSUE THREAD

**Issue by huftis** [hadley/lubridate#527]
The `as_datetime()` function doesn’t work as expected for *character* objects.

**Expected behaviour**: The datetime string should be interpreted as a datetime in the chosen time zone `tz` (UTC by default).

**Actual behaviour**: The datetime string is interpreted as a datetime in the *current* time zone (including any DST-specific stuff) and *then* converted to the `tz` timezone.

Example (as run in the `CET` time zone):

    > as_datetime("2015-01-04 03:10:00")
    [1] "2015-01-04 02:10:00 UTC"
    > as_datetime("2015-01-04 03:10:00", tz="UTC")
    [1] "2015-01-04 02:10:00 UTC"

Note that the time part is an hour off. Expected result:

    [1] "2015-01-04 03:10:00 UTC"

**Comment by vspinu** [comment]
Duplicated by #536 and fixed in cctz branch.
