### ISSUE TITLE
day light saving issue

### ISSUE THREAD

**Issue by iwccsbfb** [hadley/lubridate#531]
Assignment using `minute` function yields NA at daylight saving time. Example: 

```
> t <- as.POSIXct("2017-03-12 01:55:00", tz='America/New_York')
> t
[1] "2017-03-12 01:55:00 EST"
> minute(t) <- 60
> t
[1] NA
> t2 <- as.POSIXct("2017-03-12 01:55:00", tz='UTC')
> t2
[1] "2017-03-12 01:55:00 UTC"
> minute(t2) <- 60
> t2
[1] "2017-03-12 02:00:00 UTC"
```

**Comment by ijlyttle** [comment]
I think this is the intended behavior because the instant that you are trying to refer to does not exist in the local time zone.

**Comment by vspinu** [comment]
Yes. By default all updating operations result in NA if the civil instant lands on a non existent time (DST break, Feb 29 etc). Using `update` explicitly with `simple=TRUE` should result in valid time. But keep in mind that in the next release `simple` will be deprecated  in favor of `roll` argument (new branch [cctz](https://github.com/hadley/lubridate/tree/cctz)). Have a look at `fit_to_timeline` as well.
