### ISSUE TITLE
Arithmetic with months(1) not working - February is culprit?

### ISSUE THREAD

**Issue by msinjin** [hadley/lubridate#532]
An "NA" is returned when subtracting months(1). This appears to be a new bug.

`
> Sys.Date() - months(0)
[1] "2017-03-30"
> Sys.Date() - months(1)
[1] NA
> Sys.Date() - months(2)
[1] "2017-01-30"
> Sys.Date() + months(2)
[1] "2017-05-30"
> Sys.Date() + months(1)
[1] "2017-04-30"
> Sys.Date() + months(0)
[1] "2017-03-30"
`

**Comment by msinjin** [comment]
Hmm, seems this has to do with February...
`
(Sys.Date() + months(1)) - months(1)
[1] "2017-03-30"
`

**Comment by vspinu** [comment]
Not a new bug, but the most frequently asked question. Search for "february NA" or "february month" or "february 29 NA" on github tracker. Should give plenty of answers.
