### ISSUE TITLE
Opperation returning negative MM and SS

### ISSUE THREAD

**Issue by EdgarSantos-Fernandez** [hadley/lubridate#533]
Algebraic operation like `hours(24) - seconds_to_period(19.67 * 3600)` is returning negative MM and SS:
`[1] "5H -40M -12S"`
Is it normal?

Posted on : `http://stackoverflow.com/questions/43336420/lubridate-returns-negative-mm-and-ss?noredirect=1#comment73738545_43336420`

**Comment by vspinu** [comment]
Yes. This is normal. It should not impact the arithmetics. It's not really possible to "fix" this. See this [comment](https://github.com/hadley/lubridate/issues/503) for a bit more context.
