### ISSUE TITLE
Inf dates show as NA

### ISSUE THREAD

**Issue by ajay-d** [hadley/lubridate#541]
Is this a bug?  It seems Inf dates show as NA, but aren't NA

```
> as_date(Inf)
[1] NA
> is.na(as_date(Inf))
[1] FALSE
> is.infinite(as_date(Inf))
[1] TRUE
```

works as expected here:
```
> as_date(NA)
[1] NA
> is.na(as_date(NA))
[1] TRUE
```

**Comment by vspinu** [comment]
It's a printing methods for POSIXt. It's R's issues, not specific to lubridate. Could you please bring it there?

**Comment by ajay-d** [comment]
Thanks, you're right, it's a base R issue:
```
x1 <- as.POSIXct(Inf, origin = '1970-01-01') 
print(x1) 
is.na(x1) 
is.infinite(x1)
```
I think it's because format.POSIXct calls format.POSIXlt, and POSIXlt is NA for this case.  
I posted the issue here:
http://r.789695.n4.nabble.com/Possible-bug-in-how-POSIXct-is-printed-td4733406.html

Thanks
