### ISSUE TITLE
idea: convenience functions: ago(), hence()

### ISSUE THREAD

**Issue by ijlyttle** [hadley/lubridate#542]
These could make it easier to fix times relative to the system clock.

```r
#' @param x duration, period, or numeric
ago <- function(x, tzone = ""){
  now(tzone) - x
}
``` 

```r
hence <- function(x, tzone = ""){
  now(tzone) + x
}
```

I'd be happy to make PR if you would like.

**Comment by vspinu** [comment]
Let's not do it. Looks like nitpicking IMO.  I don't see how this could be useful in programing besides some toy examples.

**Comment by ijlyttle** [comment]
Fair enough - I can appreciate that a "balanced diet" should not include too much "syntactic sugar" :)
