### ISSUE TITLE
GitHub installation fails

### ISSUE THREAD

**Issue by hadley** [hadley/lubridate#544]
```
install_github("hadley/lubridate")
...
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/Users/hadley/R/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c update.cpp -o update.o
update.cpp:2:10: fatal error: 'civil_time.h' file not found
#include "civil_time.h"
```

R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.4

**Comment by vspinu** [comment]
I have included cctz as a submodule. install_github doesn't do recursive pull. There are open issues on both devtools and git2r for this.

**Comment by hadley** [comment]
Yes, this is why submodules are not useful for R packages at the moment, and there's no short term fix unless GitHub also bundles them in the zip files. Can you please just embed the files for now?
