### ISSUE TITLE
Feature request: Pure method for setting day, month, and year

### ISSUE THREAD

**Issue by danielcnorris** [hadley/lubridate#546]
I often find myself wanting to set the day / month / year of a date within a dplyr call to ```mutate```. I don't see how this method can be used within dplyr pipelines, since ```day(d) <- 10``` can't be called in a pipeline and mutates the existing date rather than issuing a new one.

I'd like to have a pure method that allows such behavior. Something like the following, perhaps:

```
df %>%
  mutate(pay_day = set_day(date, 15),
         same_day_in_jul = set_month(date, 7))
```

or even something more general:

```
df %>%
  mutate(pay_day = change_date(date, 15, unit = "day")
```

Do others think this would be a useful addition to the lubridate API? If it would be useful for dates, it would also be useful for instants. 

Thank you.

**Comment by cderv** [comment]
Hi, have you try `update` method of lubridate? See [Help file and example here](https://rdrr.io/cran/lubridate/man/DateUpdate.html)
It seems to me that it works as your `change_date` request.

**Comment by danielcnorris** [comment]
Perfect. That's exactly what I was looking for. Thanks!

**Comment by danielvartan** [comment]
`update()` comes from the `stats` package. When developing packages, that forces the developer to import the `stats` package, since [CRAN only consider the base package](https://r-pkgs.org/whole-game.html?q=stats#use_package).

Can't you guys develop a wrapper for this situation?

**Comment by vspinu** [comment]
@danielvartan for programming [timechange](https://github.com/vspinu/timechange) is preferred. No dependency, very efficient. Lubridate will be moved on top of it in near future.
