### ISSUE TITLE
Trouble with parsing text month %b and %B

### ISSUE THREAD

**Issue by markdanese** [hadley/lubridate#547]
maybe related to #529 

I get NA when trying to parse 02JUN2015 (%d%b%Y).  But other formats seem to be fine.  Seems to be a problem with %b and %B.

```
Restarting R session...

> lubridate::fast_strptime("02JUN2015", "%d%b%Y")
[1] NA
> lubridate::fast_strptime("02JUN2015", "%d%B%Y")
[1] NA
> lubridate::fast_strptime("2015-02-04", "%Y-%m-%d")
[1] "2015-02-04 UTC"
```

**Comment by markdanese** [comment]
I couldn't get it to install using ```devtools::install_github("hadley/lubridate")```  But good to know a fix is on its way.  Thanks very much.

```
> devtools::install_github("hadley/lubridate")
Downloading GitHub repo hadley/lubridate@master
from URL https://api.github.com/repos/hadley/lubridate/zipball/master
Installation failed: Could not find build tools necessary to build lubridate
```

**Comment by vspinu** [comment]
Is this windows? Then you need [Rtools](https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows).

**Comment by vspinu** [comment]
Yes. This was fixed some time ago. 

```R
dmy("02JUN2015")
[1] "2015-06-02"
```

**Comment by markdanese** [comment]
it is a mac.  have no idea why it isn't working.  tried reinstalling devtools.  I will just wait for the update with the fix

**Comment by markdanese** [comment]
It was a bug in RStudio.  I downloaded the dev version and can confirm that it works properly.  Thanks for your help.
